:PROPERTIES:
:ID:       5740da3f-5d0a-43f4-abd6-227a4ff092e4
:END:
#+title: awareness of Allah
* when someone doesn’t know his Lord, how can he love Allah?
:PROPERTIES:
:ID:       9ec99392-0900-4c00-b9e5-24702d731fef
:END:
- As [[id:b0c547b1-6bb9-4393-998b-20743cdf7339][Imaan ibn Qayim]] may Allah have mercy on him said,
   #+begin_quote
    The more you learn about Allah, the more you love Allah, the more we love Allah, the more we desire to meet Allah, the more we will enjoy meeting him when we meet him. *(knowledge → love → longing → delight in meeting Allah)*
   #+end_quote

* [[id:aa82dba2-4761-4b63-a07f-a2b7b52e0881][The believer will see the face of their lord]]
As the prophet peace and blessing of Allah be upon him said when he was with his companions.
 #+begin_quote
  They said to the Messager of Allah, will we see our lord in the day of judgement,the prophet peace and blessing of Allah said do you have difficultly in see the full moon in the clear night, they said no, then he peace and blessing of Allah you will see you’re lord like this. This is not to resemble what Allah look like, but how clear we will see Allah.
 #+end_quote

- Al‑[[id:1640679c-0960-4f57-8aa4-b497e27ee7c0][Nawawi]] (Sharḥ Muslim): تشبيهُ الرؤيةِ بالرؤيةِ لا المرئيِّ بالمرئي. — “It is a comparison of the act of seeing with the act of seeing, not of the One see
- [[id:0f5758bd-0049-4fc1-8c52-af7aa8a7bfbd][Ibn Ḥajar]] (Fatḥ al‑Bārī): explains “لا تُضامُّون” as “no crowding or dispute,” and affirms the comparison is in clarity/ease, not likeness of Allah.
 
* Ibn [[id:b0c547b1-6bb9-4393-998b-20743cdf7339][Qayim]] was saying this is what is required.
:PROPERTIES:
:ID:       a93fd687-9d1e-4a1a-9f8b-b19915d9cb68
:END:
However it’s not about how much we love Allah, but how much Allah loves us. We need to love him in a manner, that brings his love to us. This is by rectifying our beliefs, statements and action.
 #+begin_quote
  in hadith qudsi: [[id:4de421aa-083d-4d61-b69a-4f4d1c1d8aac][my slave will continue to come close to me with voluntary deed, until I love him]]
 #+end_quote
  - The salve of Allah doesn’t need to preform voluntary deeds, but when he is performing the voluntary deed, he is showing that he is being truthful with his claim that he love Allah
    #+begin_quote
    [[id:ba85c2ec-461c-460b-ba79-1aa5e68db4b2][If Allah loves him, he will command jibreal AS]], then jibreal will love and he will tell the other angles and then all the angels will love him, until the creation of Allah starts to love him
    #+end_quote

* We are going to study about Allah SWT and how beautiful he his, his greatness over the creation, and how nothing is similar to him and how nothing is close to him. 
    - [[id:45b02bec-cb2d-46bf-97db-f3abf6f33fc8][Allah is Beautiful and loves beauty.]]
    - [[id:b0c547b1-6bb9-4393-998b-20743cdf7339][Ibm Qayim]] my Allah have mercy on him
       quote
       Allah is Al-Jamil, the most beautiful. And how can he not be the most beautiful as everything from the earth is from the effect of Allah’s beauty
      #+end_quote
      if All of this is from the effect of his beautify, then surely he more beautiful than everything 
    - [[id:9f6feb56-0226-4b56-bf1d-c4c7ffe13cb5][Ibn Taymiyyam]] may Allah have mercy on him, said an important princple 
      quote
      There is no attribute of perfection, except that Allah has the highest level of perfection to it
      #+end_quote
      - How can the creation be anywhere near the creator, when Allah said nothing is like him “There is nothing like Him”, and “Nor is there to Him any

* This is how learn aqeeda
Aqeeda isn’t just a belief, but a belief that begins in our hearts and the effect of it is seen on our limbs.
This is not just theory in our minds, but a theory that has a result to it.

* Another example is [[id:498e3db6-9067-49c7-afaa-6865ba61102d][Allah is Ar-Rahman Ar-Raheem]]



