:PROPERTIES:
:ID:       581ddff5-392f-4285-b340-12c6c30b5404
:END:
#+title: 1. Knowledge

* We are obligated to learn certain knowledge and will not be excused
:PROPERTIES:
:ID:       ec96d7d8-630c-47c7-a642-855921faeb57
:END:
which means [[id:5740da3f-5d0a-43f4-abd6-227a4ff092e4][awareness of Allah]], [[id:6e80ecb2-97a4-4bea-b7c9-59386b82a4f0][his Prophet]] and the Religion of Islam, based on evidence
** we will be question about it (who is you’re lord, prophet and region)
we will be questioned about it and this will be the first test in the hereafter.
- Except for the few other (e.g martyr)
- The proof for this is saying of the prophet peace and blessing of Allah be on him:
  [[id:ca171420-8325-4abe-9fa7-6858f584eba6][The Trial of the Grave, 3 questions, fate of muslim vs kafir]]

   
** When Iman [[id:7344910a-ba32-4af3-9f06-a6fb18a092e6][Ahmed]] may Allah have mercy on him was asked
 #+begin_quote
  what is a the knowledge which a person will not be excused on ([[https://www.islamweb.net/ar/library/content/1044/48/%D8%B0%D9%83%D8%B1-%D8%AA%D9%84%D8%A8%D9%8A%D8%B3-%D8%A5%D8%A8%D9%84%D9%8A%D8%B3-%D8%B9%D9%84%D9%89-%D8%A3%D9%85%D8%AA%D9%86%D8%A7-%D9%81%D9%8A-%D8%A7%D9%84%D8%B9%D9%82%D8%A7%D8%A6%D8%AF-%D9%88%D8%A7%D9%84%D8%AF%D9%8A%D8%A7%D9%86%D8%A7%D8%AA][the proof for matters of creed is evident]])
  
 “Imām Aḥmad used to say: ‘Among the narrowness (poverty) of a man’s knowledge is that he blind‑follows another man in his creed (ʿiʿtiqād).’ For that reason Aḥmad b. Ḥanbal adopted Zayd’s position regarding [the share of] the grandfather and left the position of Abū Bakr al‑Ṣiddīq (may Allah be pleased with him).
  
 If someone says: ‘The common folk do not know the proofs; how can they not perform taqlīd?’—the reply is: **the proof for matters of creed is evident**, as we noted when discussing the dahriyyah (atheists); such things are not hidden from an intelligent person.
  
 As for *subsidiary legal matters (furūʿ)*, because incidents are many, and recognizing them is difficult for a layperson, and error in them is relatively tolerable, then the best course for a layperson is *to do taqlīd in those matters of one who has examined and investigated except that the layperson’s own ‘ijtihād’ is in choosing whom he follows* ”
 #+end_quote
        
** Imām al‑Lālikāʾī’s famous opening
 #+begin_quote
 in Sharḥ Uṣūl Iʿtiqād Ahl al‑Sunna ( the most obligatory matter upon a person is to know the creed of the religion)
  After this: Indeed, the most obligatory matter upon a person is to know the creed of the religion, and what Allah has charged His servants with: understanding His oneness (tawḥīd) and His attributes, and affirming His messengers— with evidences and with certainty; and arriving at the avenues to that and adducing proofs for it with arguments and clear demonstrations.
  
 And among the greatest things that can be said, and the clearest proof and sound reasoning, is: the Book of Allah—the true, manifest;** then **the statement of the Messenger of Allah (ﷺ) and of his righteous, God‑fearing Companions;** then **what the righteous Salaf have agreed upon;** then **holding fast to all of that collectively and remaining upon it until the Day of Judgment;** then **keeping away from innovations and from listening to them—those which the misleaders have newly introduced.**
 #+end_quote

