:PROPERTIES:
:ID:       926292b5-1554-485f-8f30-b8cf02f9a3a4
:END:
#+title: Fitrah


We have the natural inclination called fitrah, and a natural inclination to do goodness and even if we didn't have the Qur'an, we will know that there is a creator to be worshipped from his signs.

 #+begin_quote
 [[id:8e54132c-6eca-4411-b15d-fc6c9fc03810][The Romans (30:30)]]
 So be steadfast in faith in all uprightness ˹O Prophet˺—the natural Way of Allah which He has instilled in ˹all˺ people. Let there be no change in this creation of Allah. That is the Straight Way, but most people do not know.
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/30/30
 #+end_quote

The prophet (ﷺ) said: [[id:64f0a6e7-60ea-4f79-90ad-82c11b399393][No child is born except on Al-Fitra (Islam)]]
 #+begin_quote
 [[id:b4eb33b7-e994-4121-b5f4-2239370b8cc3][The Sun (91:7)]] And [by] the soul and He who proportioned it
 [[id:a68e80f3-91b0-4452-b23a-0c470f6d655d][The Sun (91:8)]] And inspired it [with discernment of] its wickedness and its righteousness,
 #+end_quote

Mankind has the innate ability to discern between good and bad, without needing the Qur'an and Sunnah. An innate program, that can't deny the lordship of Allah (Creator, Eternal, All Powerful), they know the universe can't be created out of absolute complete nothingness (the absence absolutely everything this also include matter and energy), but by the creator who is eternal.

The Shari'a guards our fitrah and not to corrupt it e.g. having shyness, lowering the gaze.
