:PROPERTIES:
:ID:       17aa6a07-0350-4ea3-9f26-96e589cfeda4
:END:
#+title: The heaviness of the revilation
#+filetags: :hadith:

حَدَّثَنَا إِسْمَاعِيلُ بْنُ عَبْدِ اللَّهِ، قَالَ حَدَّثَنِي إِبْرَاهِيمُ بْنُ سَعْدٍ، عَنْ صَالِحِ بْنِ كَيْسَانَ، عَنِ ابْنِ شِهَابٍ، قَالَ حَدَّثَنِي سَهْلُ بْنُ سَعْدٍ السَّاعِدِيُّ، أَنَّهُ رَأَى مَرْوَانَ بْنَ الْحَكَمِ فِي الْمَسْجِدِ، فَأَقْبَلْتُ حَتَّى جَلَسْتُ إِلَى جَنْبِهِ، فَأَخْبَرَنَا أَنَّ زَيْدَ بْنَ ثَابِتٍ أَخْبَرَهُ أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم أَمْلَى عَلَيْهِ لاَ يَسْتَوِي الْقَاعِدُونَ مِنَ الْمُؤْمِنِينَ وَالْمُجَاهِدُونَ فِي سَبِيلِ اللَّهِ فَجَاءَهُ ابْنُ أُمِّ مَكْتُومٍ وَهْوَ يُمِلُّهَا عَلَىَّ قَالَ يَا رَسُولَ اللَّهِ، وَاللَّهِ لَوْ أَسْتَطِيعُ الْجِهَادَ لَجَاهَدْتُ ـ وَكَانَ أَعْمَى ـ فَأَنْزَلَ اللَّهُ عَلَى رَسُولِهِ صلى الله عليه وسلم وَفَخِذُهُ عَلَى فَخِذِي، فَثَقُلَتْ عَلَىَّ حَتَّى خِفْتُ أَنْ تُرَضَّ فَخِذِي، ثُمَّ سُرِّيَ عَنْهُ، فَأَنْزَلَ اللَّهُ ‏{‏غَيْرَ أُولِي الضَّرَرِ‏}‏

Narrated [[id:0a257606-e759-4d56-87d3-8ef232212ecb][Zaid bin Thabit]]: That the Prophet (ﷺ) dictated to him: "Not equal are those of the believers who sit (at home) and those who strive and fight in the Cause of Allah." Zaid added: Ibn Um Maktum came while the Prophet (ﷺ) was dictating to me and said, "O Allah's Apostle! By Allah, if I had the power to fight (in Allah's Cause), I would," and he was a blind man. So Allah revealed to his Apostle while his thigh was on my thigh, and his thigh became so heavy that I was afraid it might fracture my thigh. Then that state of the Prophet (ﷺ) passed and Allah revealed: -- "Except those who are disabled (by injury or are blind or lame etc).

Sahih al-Bukhari 4592
https://sunnah.com/bukhari:4592
