:PROPERTIES:
:ID:       6e80ecb2-97a4-4bea-b7c9-59386b82a4f0
:END:
#+title: his Prophet
* What is knowledge?
it is to learn about Allah, the prophet Muhammad peace and blessing of Allah be on him.
* What is his station in from of Allah?
:PROPERTIES:
:ID:       c1dd4f76-80cd-4b56-bfc5-9c4867302fc0
:END:
the prophet peace and blessing of Allah of be on him: said [[id:64e94fd6-234e-458c-bd28-b136c864bed4][I am the chief of the children of Adam on the Day of Judgement]] and this is not from arrogance
- This is the right that Allah has given him peace and blessing of Allah be on him and a station which we all witness, *so no man step on this earth or created being greater than him*. Muhammad peace and blessing be upon him I greater than the Anbiya, but they are all great, this is the right that Allah has given as he is the master of the children of Adam
* hence it is a right he has we love him peace and blessing of Allah be on him, more than ourselves, our parents, children, all of mankind.
:PROPERTIES:
:ID:       32fd93d7-c48c-4251-8f1c-4a0f4de38e6e
:END:
- [[id:d59012b8-5177-443a-99af-ed51fd05a6aa][To love the Messenger is a part of faith]], and is apart of [[id:29b3fb81-2ef5-469a-a2e8-b9e7adef8cbe][sweetness of faith]] we also find [[id:ca682611-13dc-4d42-836f-2b2a272b6eed][Umar (may Allah be please with him) choosing to love the messenger more than himself]]. He peace and blessing of Allah loved us so much that the first thing the prophet peace and blessing of Allah be on him, when granted to speak, is my [[id:81fecea0-9b65-4608-ad6a-7ae8b557ee92][“ummati ummati”]]. He peace and blessing of Allah saved this "[[id:50eb90fd-c9ef-48eb-8cff-6099ab4728ba][special supplication]]" for us and not for himself. [[id:135afed0-779f-490f-9259-d7717bb2c459][Allah said: "Jibril, go to Muhammad (ﷺ) and say: 'Verily, We will please you with regard to your Ummah and will never displease you"]].
** We must learn about him until he becomes the most beloved to us
- if it wasn’t for Allah and then the Prophet peace and blessing of Allah be on him, then we wouldn’t know how to be Muslims and know how to please Allah and not anger Allah.
  - as the [[id:d73877f2-1d5d-4e34-a2a6-9bd3395c3974][only accepted religion is Islam]].
  - This mean after Prophet Muhammad peace and blessing of Allah be on him was sent, it abrogated everything before it.
    - When Musa was sent, he was sent with Islam, then his people distorted the religion, and every other prophet that came, the religion was distorted by it’s people.
      - Until Muhammed peace and blessing of Allah be on him came, and [[id:6543a4c0-06bb-478d-b519-17820c3b5a56][Allah said he will guard Islam]]. 
      - This religion will not change and it will always send the message throughout time, even if people will try to distort the Religion


