:PROPERTIES:
:ID:       6fe4d2f5-79f3-4c0e-a633-93fb791e837c
:END:
#+title: thalatha lesson 6

* eman
to afirm and bleive in a manner that you prove it

eman is statmenet and action and belieft and increase with obdienade and deceseae with diobediance
statement of the heart and the statement of the toung
action of the tought
action of the heart (e.g hope) and the limb (e.g salah)

so it has 5 part
- bleieft
- statemetn
- action
- increase with obideince 
- decrease with disobdieance

certainty is of differenct lvel 
[[id:f319dc15-6a70-4b12-b8bc-cbe26341d269][The certainty of being told vs witnessing]]
hence eman increase with obdience and certainty increased with emaan

eman can compose the entirer relgion

- now general emaan the 2nd stag
  - it is something around 70 branch
    - these are the wording of a hadith
    emaan is of 3 types
    - statmentes of the tought - the shahadah
    - actions - removing something harful from the street
    - heart - shyness
    it increase with obdiance
    and descresses with disobdiance

    any statement, action and belife in the heart, that pleases Allah is emaan 

 It consists of more than 70 branches. The heist of them is saying Laa ilaaaha IllaaAllah and the lowest of the is moving a harmful object from the road. Hayaa (modesty) is a branch of from Eman. 
- this is coming from a hdaith of abu hurairah

  musa said teach me soemthing
  - Allah said say the shahdah
    - he wanted something exclusive
      - but allah show that this outweight everythign from the eart
the lowest part is to remove eosmething harmful
- shyness that is praiseworthy
  - not the one that stop you from getting knowledge

the specific part of eman (inner actions)
it's pilars are 6
 - these are all matters of the unseen
  - they can't be proven to us
    - this is our belief
  - if you deny it, then you are a disbeliever

 - Allah
  - must bleief
    - that Allah exsist
      - he is the one true lord
      - he deserve to be worshiped
        - and he is perfect
---------

1. angles
   - they are a creation of Allah that are hidden from us and they are worhsipers of Allah
     - They don't possess anything from is lordship
       - Allah created them from light
         - he has gifted them to worship Allah contantly without disobdiance
           - the glorify Allah in the night and day
             - they are a large number that we can't count them
               - e.g al bayt ul mamoor
                 - 70,000 was praying there, when they leave they don't get the chance to come back there
     - 4 key point
       1. they exist
       2. beleive in their names that has been toughts e.g. jibreal, we must believe in it from an authentic source 
       3. believe in their attributes
          - believe in their specific description
            - e.g 60,000 wings hadith
              - coming in a form of a man hdaith
                - The specific roles that the perform
                - jibreal repsoible for revelation
                - mikaeel - disitbution of rain 
                - isrfeel - to blow the thrupet
                - malik ul maut - the angle of deal
                - the angle of wriing good ded
                - grave munkar and nakir
                - the angel that protect us 
       4. we learn this to prove our emaan
          - it show the greatness of Allah
            - they are so great, but Allah is greater
              - we should thank Allah that Allah has taken care of us by sending us the angles
              - taking care of our deeds, have them write donw 
              - to love the malika as they worhsip Allah
                - the have a high station and we would like for them to love us
                  - e.g haidth of those who are close to Allah
2. books
   - that has been reavled 
   - as a mercy and mean sof guiance for the creation
     - so that they could be saved in this life and the next
       - sent different book to guide them into the light
         - to take care of the creation
           - and it's is from his lordship
             to take care of his creation
   - 4 pillars  
     1. they were sent with truth
     2. we believe in the specifc name of the book
        - quran- given to muhammed (ﷺ) 
          - towarh - musa
            - injeel - esa
              - zaboor - dawood
                the scroll of ibrahim and musa
     3. belive that which has been metntion in it
        - beleive everything that was in the quran
          - that which was in the perviouse scripture before they're are corrupted
            - hadith don't say it's correct or don't say it's correct
     4. we act upon our book from that which has not been abrogated
        - his revelation is based on his wisdom
          - e.g the abrogation of alhchol
            - the authetnic text will never conflict with a sound mind
              - e.g. a fabriacate narration, or him understanding things for his desires
                - allah will keep telling us to reflect and ponder
                  - how can he ask us for this if we can't think about a sound mind for it
                    - to not know something, doesn't mean that things is not known
                      there are many matter that many people don't knwo
                      - but it deoesn't say everyone won't know, so there are people know some of the widome of it
                        - the shari'a look at what is benifial and harmful
                          - these are all from the wisdom of Allah 
3. the messenger
   - they are men that Allah reveal the revation to and commanded to convey it
   - sometime a person will have an insperation like the mother of musa
     - but shee not a prophet or messeenger
       - if they must convey the messeage, then a mensger
         - nabi vs rasol
           - ibn taymiyah
             - a nabi is someone was given revaltion and told to convey it to the people who already belive  
               - a rasol is to the disbeliving people
           - ever messenger is a prophet, every rasol is a nabi 
             - but nnot every prophet is a messnger, not every nabi is a rasol
               - nuh was ther first person taht sent to the desbleiving peopl e
                 - adam was for the first beleiving people
                   - up to 10 centries
                     - these messenger are human being but are the best of human beings and would make miustake like humans, however tehy are correct by Allah immediately
                       e.g the example of Nuh when his son died, Allah said he is not form his family, don't ask about something you have no knowledge
                       - yunus left his people upon disbleift
                         and then he repented
                         - musa killed and man and repeont
                           - the prophet (ﷺ) turn around and frowned
                             - when abulah ibn maktton and blind man came during the dawah of the leader of quraish
                               - and immediate turned by to Allah
                                 - Allah has forgive the Prophet (ﷺ)
                                   - they are human being
                                     - hadith indded i am a human being and i forget and if i forget then remind me
                                       - the prophet (ﷺ) was leading the peole in salah
                                         - he (ﷺ) was angry and nobody say anything
                                           - the man with long arm said did you forget or did the salah become short
                                             - the prophet thought he prayed 4 rackat and he affirmed that it hasn't become shorter
                                               - he stood up to preform 2 rakat , the postrated of forgetfulness
                                                 - however the revelation will always be preserver
                                                   - the prophet can never do any sin that will bring doubt to the revelation
                                                     - so What ibrahim did was a white lie, he said the bigger of them did this.
                                                       - they thought it was the bigger status and he meant his thumb when he pushed the idol.
                                                         - they mistake and seek forgive and Allah forgive them
                                                           - 5 of them are the greateest
                                                             1. muhammed (ﷺ), the master of the children of adam
                                                             2. ibrahim also the khalil
                                                                the two khalil 
                                                             3. musa 
                                                             4. Isa
                                                             5. noh
     - last two are different, these are the 5 grestest messengers
       - we do not differe between them, how can we say some is bertter than other. what does this verse mean
       - we don't differiate to disrespect betwen them eachother
         - it is from eman to love them all
           - every miracil that was given the prophet (ﷺ) was also given it,
             - and sometime Allah will allow him to show this to mankind
               - but out of respect he didn't do it for the other messengers
   - the 4 point of eman
     1. we believe their orignal messenger is the truth
        - if you disblieve in anyone of the messeage then you have disbelieve all the other messenger because they all come from Allah
     2. we believe they're names 
        - 25 only are mentioned
          - The 25 prophets mentioned in the Quran are Adam, Idris (Enoch), Nuh (Noah), Hud, Saleh, Lut (Lot), Ibrahim (Abraham), Ismail (Ishmael), Ishaq (Isaac), Yaqub (Jacob), Yusuf (Joseph), Shu'aib (Jethro), Ayyub (Job), Dhulkifl (Ezekiel), Musa (Moses), Harun (Aaron), Dawud (David), Sulayman (Solomon), Ilyas (Elijah), Alyasa (Elisha), Yunus (Jonah), Zakariya (Zechariah), Yahya (John the Baptist), Isa (Jesus), and Muhammad.
            - there are other name
              - lukman
              - dul karnai
              - qalut
              - khidir/khadir
     3. everything that is authentically reported we accepted it
        - news can't be abrogated
     4. we act according to our shari'a the one taht the prophet (ﷺ) sent
   - non of the shabah are better than the messenger,
     - after them is abu bakr as sadiq
4. to bleivie int he last day
   - a different life completely the last day and nothing will be repeat and it will be a new life,
     it has a name in every letter of the alhpabet, to show it's importance
     - e.g
       - the day of standing
   - it is every from the moment the unseen begings till jannah
     - include the reward/punishment of the gramve

   - 3 point to belive in
     1. life give to the dead - resurection
        - for the last day, the people will be raised bare footed and be naked
          - aisha was wondering won't people look at each other, but we will be in greater fear and only worry about ourself
            - it will be too sever for us
     2. the hisab
        - everyone will be accoutanble
     3. jazah
        - the reward
          those enter paradise will never leave it
          - these have already been created and will remain in existance for enternity             
          - every one has there place there
          - The beleiver will inherity the place of the kafir in jannah
            - the kafir will inherity the place of the believers in the hell fire 
   - benifits
     - prevents us from faling into sin
     - encoruge us to do good deeds
     - don't get our heart attach to the affares of this word
     - it can be proven with the mind logically
       - Allah show us he bought people back to life
         - liek the man who was in town
           - Allah took him for 100 year and then he was bought to life
           - another example
             - you will find the eart that is dead and bought back to life
               - you take the seed and plant it after it has died and it can come back again
                 - the onw who has broght you to live the first time then it will be easier to do it again
5. to belive in qadr
   - the good and the bad of it
     - all of the Action is of Allah is good
       - evil is not attributed to allah
         - the hdaith realted to the good and bad is realted to us
           - for us it is bad to which is apparent
             - perhaps we will dislike something but it is better than us           
             - qadr is the one that regulats tawheed
     there are 4 part of it
     1. Allah know everything that has happened and it fine details
        - to Allah belong the keys of the unseen
          - he know what is in the land and sea
            - he know when the leaves drops
              - he know the where the grains are place

     2. everything that is currently happen
        - nothing excape his knowledge
          - he know the details

     3. everything that happen in the future
        - nothing will happen contray to his knowledge

     4. and if it was different or not Allah will still know
        - the disbeliver asking to be return
          - they will do exact what they shouldn't do
            - even if they return Allah know the outcome
            - this show perfection in knowledge
              - Allah has complete knowledge of Everything
                - and even if the something didn't happen Allah will still know the outcome of it 
             
   - everything is written down
     - Allah has writen before he created the heave and earth by 50,000 year hadith
       - the propeht (ﷺ) said when he first created the pen he said write, the pen spoke and said what should i write
         - Allah said write everythign untill the hour has been established
         - Who ever dies and not believe in this is not from the believers
         - this is beyond our own comprehension  
           - we won't be able to undertstand the mangitde of the book
             
   - nothing place part in the creation except that he has willed it
     - and you do not will except Allah has willed

   - Allah has created everything
     - Allah has created you and you're actions

if Allah will it and created it are we forced or do we have free will
- who every wnt to be up right let him be upright
  - if you want to do then do it, this is the free will
    - no one can deny the fact that we have free will, if you want to raise youre hand you'll raise your hand
      - those who chose to do it chose it, no one was forced
        - and Allah has will to raised your hand
          - and those who didn't Allah has chose it
            e.g a person want to take a train
            - he got to the platform
              - but on that day Allah willed that the train is going to be leaving earlier
                - the man willed to get on the trained, but Allah will that he didn't
                  - the man chose to go on  that time and he got that time, but if he would have came earlier he would have go the train, but Allah has not willed this, hence Allah (ﷻ) will is dominate and while you still exercised you're free will and was not forced to do any action. 
                  - we will not know until the action was performed 
                    - hence we can not depend on his will, that we need to perform actions make intention and strive and then we will what the will of Allah is
                      - Allah know what we're going to do and choose
                        - even if you don't do the action, you'll still be rewared with the action 
    - some people will use this arguement to commit sin
      - Allah adress them in the quran
        - that they won't even be able to commit shirk if it was the case
          - and Allah still punished them because this is what they choose to do
            - Allah sent mesenger to warn them
              - and they won't have any excuse to establishe evidence, if they're was force then there won't need to be a messenger
                - hadith
                  - everytone seat is written on the hell fire and heaven
                    - so someone said should we just follow the qadr
                      - the propeht (ﷺ) said no perform deed and what ever dded you perform it will be easier to follow that path
                        - Allah will facilate him with path of goodness, quran ayah
                          - whatever someone was created for that path will be easy for him hadith
                            - he know what this person will go and treverse is, what haram and hallal he will do what fard he will do
                              - when Allah see he want goodness he will make good easy for him
                                and the person will take whatever path they want, Allah faciliates it
                                and if he dind't chose it then Allah did not faciliates
                                - Allah do not hold anyone accont the ability you can perform
                                  - fear Allah as much as you can
                                    - you won't be accontable for that which you can't bear 
                                    - Allah has create in every human being a desire and ability/strenmght
                                      - for everyone this is different
                                        - for everyone have different levels of its  
                                        - when desire is put with ability it forms an action that the person intended to and that when the accountablity comes
                                          - hence Allah he said he created you and you're action
                                            - because he created your desire and abilite
                                              - you can have them both
                                                - but you are controling that desire by not puting the ability with the desire to carry out
                                                  - because you didn't carry it out, you won't be accontable, even if the desire is something which is extme
                                                    - it is only when you carry it out ability to form the action, then you will be accoutnable
                - for example, people have a desire of haram and say that i was created like this how can i not carry this out and use it as a reason to leave the relgion and practice their desire such as being gay 
                  - then what is the difference between this person and the one that wish to commit zina or any other crime
                    - we say you won't be accountable for having the desire, but you'll be accountble for what you carry out
                      - protect yourself from this to seek the pleasure of Allah 
                      - don't put the desire and ability together and you have pass the test 
                      - they look at qadr to commit the sin, but here we look at it for a reason to not commit the sin
                        - hence who ever intent something good adn not able to do it, he will be rewared for the good intention 
                        - and who ever intend to do something evil and doesn't do it, Allah will write good deed for it
                          - this is a mecy from Allah
                            and you're rewareded for this
                            - the qadr is from the unseen
                              - you can know it only after it, and you have the choise before it, and you ahve to use youre free will to find out what the qadr of Allah
                - When it also come to the worldy matters
                  - you give two path a good (make you rich, stronger ) one and a bad (you could die or become disabled and weak) one, choose the path, everyone will chose the good one and now one will blame qadr on which path he want to treverse on
                    - so why are we not using this reason for this deen but only for that of the dunya
                         
                - So we know which path will take us to Jannah and Jahhanam
                  - Allah has created the desire and ability for us
                    - the general dessire we have
                      - we won't be accountable for this
                        - this is why the person carries out without the intentio nhe won't be accountable
                          - e.g accently trip to look like he bowed to an idol
                            - no, the ability is there but the intention is not there
                              - when the abilit is there alone or desire is there alone
                                - you won't be accountable, and Allah created them both
                                  - hence when you do both it will create the action, hence that why Allah has created you're action
                                    - and know you'll be accountable
                                      - Allah does not force the creation, but thye chose what they want and they will be accountable
                                        - during umar time and man stole something, then cut his hand
                                          - he tried to blame the qadr of allah so umar said we will cut you're hand by the qadr of Allah
        - what is the beinifit on this,
          - is that we rely on Allah, the means can or can't work.
            - we know it was only due to Allah that he allowed it
              - hence we ask Allah to assit us to remember and worship Allah
              - we don't over praise ourself and attribute it to Allah
              - when a person is face with a camiity what every was going to affilt is was never going to miss him and what ever missed him was never going to hit him
                - this is from Allah,
                  hence we can use qadr as a excute for calamity
                  - eg. musa vs adam hadith and quran
                  - sometimes it is used to raise the status
                    if Allah loves them, Allah test them
                    - the test is used as a expiate
                      - All of the action of Allah is good and we don't attribute anything evil to Allah 
                        - what you see is limited and can only see limited, but the person who has faced it will want it again, he'll be in the heart of a green bird roaming around the thrown of Allah
                          - evil is not attributed to Allah and only goodness 
                          - Allah does not decree everything except from the his ultimate wisdom
                            - we not it is wise, because Allah is the most Wise
                              
* ihsan
the muhseenon
**  [[id:91e4be53-1973-4481-be3d-05dce40e0cb3][Mushahada]] - worship Allah as if he could see him, but not be able to see
  #+begin_quote
   None of you will see Allah until you will pass away
  #+end_quote

 A sahabah narrated, [[id:61aec9e5-5314-4fa6-bd4b-2c7372ca17dd][there are too many voluntary act, so which act can someone do that will encompassed all of them. That is to constantly remember Allah.]]
 - ibn qayyim said no will reach the level of ihsan other than those who frequency move their tought
   
 If you are in constant remembrance of Allah, then how hard will it be to even come close to the sin, how can a person sin while remember his lord, how can you fall into evil deeds when you’re doing the good deed known that Allah is watch you. Like when you’re are saying Allah hu akbar, you remember how weak and deficient you are. As Allah [[id:076b0d9a-dc90-40e4-8f60-5752c8678003][say’s you will not pierce trough this earth and you’re not going to reach the mountain in height]]
 - Where does arrogance come from, how can you be proud, when you beginning was a droplet of fluid, while you’re alive you holding impurities in your stomach, when you die, you will turn into a rotten corpse that people will despise because of the pungent foul smell.
 - You’re beginning, middle and ending is despised, so where had this arrogance come from. So the slave of Allah, will say Allah hu Akbar, recognizing that Allah is the greatest and how weak we are and in need of Allah constantly. It make him repent to Allah and lead him to more good deeds. 
 - So he keeps his tongue moist with the remembrance of Allah, what does it do? It encompasses the entire sharia of Allah, as it lead us to every path of goodness and away from harm and evil. 
So this is the religion of Allah, learn about it and perfect it (statement, action, beliefs); to become like the Prophet peace and blessing be upon him,
 #+begin_quote
  [[id:b2fef51c-93a4-4141-91d2-36c84cb1828b][like when Aisha may Allah be pleased with her said his etiquette are that of the Quran.]]
 #+end_quote
Every good quality you’ll find you’ll find it on him and every evil quality, he is free from it, peace and blessing of Allah be on him. Every act of worship you’ll find him doing it, every act of sin, you’ll find him free from it.

** Muraqaba - worship Allah, knowing you are being watched but not at the level of seeing
 From the examples of the creation, when a person is being watch the preform the task at hand better, than if he was not being watched.
 Now working when someone is in person vs using a camera is not the same, and the task at hand will be preformed different, and not at the same quality.

 However with ihsaan, is knowing that Allah is always watching and always aware of what you do, the Ever-Living, the Self-Sustaining, free from any deficiency, the One and only Who is possessed of ultimate greatness and the One only Who is exalted in His Essence, and is exalted in His attributes,  with that knowledge you act according to, think according to it, behave according to it. everything you do is according it, knowing that your lord is always watching, this is to be conscious of Allah, then the task that will be performed will be to his best ability
 
** The certainty of being told vs witnessing
:PROPERTIES:
:ID:       f319dc15-6a70-4b12-b8bc-cbe26341d269
:END:
we will study about Allah, his greatness, his rights and his messenger, we will build the certainty to the highest degree 
  #+begin_quote
   The Rivalry in world increase (102:5-8)
   [[id:30547bd0-fe40-4dee-af9e-ed8192c1bdf3][No! If you only knew with knowledge of certainty..]]
   [[id:344da55d-db52-42fb-9cd9-d3cb4bed0f03][You will surely see the Hellfire.]]
   [[id:2e1d4e80-c58a-420f-8e34-843f8fc33a3b][Then you will surely see it with the eye of certainty.]]
   [[id:cc85cc64-3a53-4680-ac18-9cdfd086d872][Then you will surely be asked that Day about pleasure.]]
     #+end_quote
you see the difference between the knowledge of certainty vs eye of certainty, hence our aim is to *increase our certainty*.
*** [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Abdullah Ibn Masoud]], was asked what is emaan, he said emaan is certainty.
When a person is certain, he will not leave the obligation, stay away from haram, do the voluntary act and stay away with that which is disliked

*  The third principle

between the prophet (ﷺ) till adnan is 21 people, from the mother side it both meets at kilab, so aminah bin wahab ibn abu nanaf ibn zaharah ibn kilab.

from the creation he is deservering of the salat ([[id:57a6968f-c3f5-401f-a9ec-36e89cf264ad][ﷺ)]]
- he warned people of shirk and erdicated it
- called people to tawheed    



quran ayah
- the reason for this verse is for the muslim who did not migrate
  - did not call them oh disbelivers, people who have left the relgion
    - they are still called muslim
- hijrah mean migrating to a better land not just a muslim land, but a better land that will make it easier to practice you're deen.
  - e.g the land of absidya
    - what is the ruling of hijrah
      - if they're unable to identy of theire identiy/islam
        - if they're able to migrate
          - hijrah is obligatory on this person
      - 2nd case
        - hes able to establish his relgion
          - and he is able to migrate
            - for him it is recommended
      - if he's unable to make it 
        - Allah will forgive him
          - Hijrah will come a end until repensece will end
            and repsence will end when the sun rises from the west hadith
            - no one can say it been abogated
              - there no hijrah after the conquest hadith
                - beacause makkah has not become the land of Islam
                  - hijrah will remain until the enemy ar fought hadith
when makkah
- revelation related to the inner belief
  - tawheed
  
when in madinah
- revelation related to the legislation of islam
  - e.g zakat, jehad

There prophet (ﷺ) was sent of all of mankind and to the jinn and Allah has complete the relgion, then general Islamn and the secific. No prophet has came after. This verse was this is the day you're relgion has been perfect is on the day of hajj during the day of arafat.


the aim of a muslim is to give them the evidence to bring people to jannah and not prove the evidence against them


Allaah sent down the messengers as a warner
- to give gladtind and warning for people
- nuh being the first and the last being the Prophet (ﷺ)
  - and the creation will come too nuh when seeking intervention
    - every nation was sent a messenger
      - to worship Allah alone and stay away from the tagoot
        - to disbelieve the tagoot and to believe in Allah
          - tagoot mean
            - ibn qayyim said
              - that which a person has trangress the limit for that which he worship, follows or obeys. That this has been made a tagoot and is worhsiping beside Allah.
                - the thing itself might not be a tagoot but will make it e.g. esa
                  - to follow other than the guidance of Islam and to make it the path
                    - to give someone else thr right of legislation
                      - the right is only with Allah to legislate
              - but tho peole who are worshiped and pleased with it a tawageet
                - the reason why Allah sent the messenger to erdicate their evil and foolishness 
          - uncess is in two categories
            - known to some but not to everyone
              - eg hiding a treasure 
            - the gayeeb
              - weather the person is pieous or not will go jannah or not
                
There is not compulstion in relgion                
- you can't force anyone to enter into Islam
  - hence who every changes his relgion kill him hadith
    - if there is no colpostion then he can leave when he want, but this is not the meaning of the verse, it mean you can't be force to enter into it 
  - if yyou disbelieve in the tagooot
    - then you will have entered into Islam



*** Belief in Allah
*** Belief in the angels
*** Belief in the Books
*** Belief in the Messengers
*** Belief in the Last Day
*** Belief in Qadr
* Iḥsān
* The third principle

** Lineage of the Prophet (ﷺ)
** Aim of the Muslim in da‘wah
** “there is no compulsion in religion”
