:PROPERTIES:
:ID:       e4d3eb72-0720-4f1b-9671-43360f60aff2
:END:
#+title: 3. Calling to it
* Yoe can’t call something to something you haven’t learned. You can’t speak without knowledge.
- [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Abdullah ibn Masood]] advising that anyone who knows should speak, but whoever does not should say “[[id:fb3e12ab-1acc-4e8f-b6db-65c460a58c5a][Allah knows best]],”
- Imaan Malik used to [[id:c3382935-f014-40ac-9afc-4d0d53ca6b5c][say I don’t know]]
  - I put myself between jannah and the nar, if i act with knowledge it will be my path to jannah, and without it then it will be the
* Speak with knowledge and integrity
:PROPERTIES:
:ID:       9558efc0-524c-4d80-8577-92b39e2be8c8
:END:

 #+begin_quote
  [[id:408d57a2-a0a1-4cb0-b810-27dacb323e37][The Bee (16:116)]]
  And do not say about what your tongues assert of untruth, "This is lawful and this is unlawful," to invent falsehood about Allāh. Indeed, those who invent falsehood about Allāh will not succeed.
  — Saheeh International
  https://quran.com/16/116
 #+end_quote

**  Acquire knowledge first -> act -> then call to it
 #+begin_quote
  [[id:17a75c6a-779a-44f1-8f75-9bc1d3fc849a][The Cow (2:44)]] 
  Do you order righteousness of the people and forget yourselves while you recite the Scripture? Then will you not reason?
  — Saheeh International
  https://quran.com/2/44
 #+end_quote
-----
 #+begin_quote
  [[id:aceaae52-b6de-4cca-b419-3e5145203b7e][The Ranks (61:2)]]
  O you who have believed, why do you say what you do not do?
  — Saheeh International
  https://quran.com/61/2
 #+end_quote
 #+begin_quote
  [[id:d9593916-fdb2-4866-a21c-2f7c3f7d4934][The Ranks (61:3)]] 
  Greatly hateful in the sight of Allāh is that you say what you do not do.
  — Saheeh International
  https://quran.com/61/3     
 #+end_quote

* The best speech is to call to Allah,
:PROPERTIES:
:ID:       822c3c8d-f193-44f9-a2ca-02db85117667
:END:
 #+begin_quote
  [[id:c1c8e125-852d-4ff7-9d96-2581ec33ff3d][Explained in Detail (41:33)]]
  And who is better in speech than one who invites to Allāh and does righteousness and says, "Indeed, I am of the Muslims."
  — Saheeh International
 #+end_quote
** Shabaha differed, who is better the Muadin vs Imaan,
:PROPERTIES:
:ID:       c7af5509-9ad9-46b2-a585-1ce251dc6cd2
:END:
as the muadin is calling the people to Allah
*** view of Aisha, is the one who is calling to Salah is more virtuous than the one who is leading the Salah (the transmission is weak)
**** [[id:6c2f9562-afd4-4189-82c9-4e44dc62db9f][The Virtue Of the Adhan]], And The Shaitan Flees When He Hears It and [[id:caf75e0b-fd7a-4812-a461-d68c96925241][people will draw lots for pronouncing the Adhan]] 
Allah also says:
 #+begin_quote
  [[id:8cb9669d-42c9-45be-9727-cb4fe6b86978][Joseph (12:108)]]
  Say, "This is my way; I invite to Allāh with insight, I and those who follow me. And exalted is Allāh; and I am not of those who associate others with Him."
  — Saheeh International
  https://quran.com/12/108
 #+end_quote

* 3 types of knowloedge
:PROPERTIES:
:ID:       258fdf5e-8b36-4d39-a257-0bba1a1d4426
:END:
This is dawah, the way of the prophet peace and blessing of Allah be upon him
** 1. the thing that we’re calling to, the Islamic text, the particular ruling of the sharia, the belief 
:PROPERTIES:
:ID:       490080e2-81ac-4a07-90dd-0438dfa67bc3
:END:
** 2. knowledge of the person we’re calling, know his situation/condition 
:PROPERTIES:
:ID:       56b149f7-b8c9-49fc-b719-a8d12c9d0d3a
:END:
** 3. knowledge of the possible repercussion to society 
:PROPERTIES:
:ID:       6f39b074-0ecf-4b02-88e3-4a2b9ca7ce89
:END:
