:PROPERTIES:
:ID:       18b3ad1e-8b3e-4e19-b5cc-e6a581593ecc
:END:
#+title: Al-Bukhaari
#+filetags: :Imaam:

* Bio
*Name*: Imaan Abū ‘Abd Allāh Muḥammad ibn Ismā‘īl ibn Ibrāhīm ibn al-Mughīrah ibn Bardizbah al-Ju‘fī al-Bukhārī
*Born*: 194AH
*Died*: 256AH
*Age*: 62 
*Titles*: Amīr al‑Muʾminīn fī al‑Ḥadīth (Leader of the Faithful in ḥadīth)

* Teachers
- *Yaḥyā ibn Ma'īn* (d. 233 AH)
   The pre-eminent critic of narrators (rijāl). Al-Nasā'ī classed him with the top four of that age. 
- *Alī ibn al-Madīnī* (d. 234 AH)
   Bukhārī said: “I never felt small before anyone except 'Alī ibn al-Madīnī.” A master of 'ilal (hidden defects).
   His teacher said, Bukhari has never seen anyone like him self
- *Isḥāq ibn Rāhwayh* (d. 238 AH)
   senior imām; his “why don’t you compile a book of only ṣaḥīḥ ḥadīth?” remark sparked Bukhārī’s project. 
- *Ahmad ibn hanbal* (d. 241 AH)
   Bukhārī met and learned from him; there’s very little direct narration from Aḥmad in the Ṣaḥīḥ (Ibn Ḥajar notes one direct spot and one via intermediary). 

* Students
- Muḥammad b. Yūsuf al-Fīrabrī (d. 320 AH)
   main transmitter; most printed editions descend from his recension. He said, “~70,000 people heard Ṣaḥīḥ with me.” 
- Imām Muslim ibn al-Ḥajjāj (d. 261 AH)
   attended and narrated from al-Bukhārī. One of the foremost students; author of Ṣaḥīḥ Muslim. 
- Imām Abū ʿĪsā al-Tirmidhī (d. 279 AH)
   explicitly described as a pupil of al-Bukhārī in standard bios; author of Jāmiʿ al-Tirmidhī. 
- Imām al-Nasāʾī (d. 303 AH)
   counted among those who narrated from al-Bukhārī; author of Sunan al-Nasāʾī. 
- Muḥammad b. Naṣr al-Marwazī (d. 294 AH)
   also listed among those who narrated from al-Bukhārī (major early imām). 

* His father was a pious man
His father a student of Imaan malik, Ismael, was known for piety and scrupulous earnings. Reports mention he said he did not know of any unlawful coin in his wealth. He died when al‑Bukhārī was young.

* Complete blind when he was young
his mother say a dream and Ibrahim coming and saying Allah (ﷻ) has return his eyesight 
his mother used to make allot of dua for this, and when she woke up to see Bukhaari and see that the dream it was true

* He stood out in memory and understanding
Memorised Qur'an at 7. He memorised narrations, he went of the lesson of the senior teacher ad-Dakhili, he was narrating hadith of abu al-zubayr, at the time and raised his hand and said you did not narrate from Ibrahim al-Nakha'i. Imaan Bukhaari said go back to your book and check, he went back to his book and he made the mistake and ask him to correct him every time he made a mistake. 

* Al-Tarikh Al-Kabir 
He memories everything about the narrator and compiles the book at the age of 18. He went for Ummrah and stay in Medina, he sat at the rawdah and he would sit the in the full night to write tariq al kabir, it printed in 21 volumes he write all the biography of the narrators with details, (birth/death, reliability and kunays).
- There was many stories in so he remove it to some, out of fear it will become too large.
- A Scholar took this kitab to the leader of bukhara and said should I show you magic, and he showed this kitab. He written the biography of 40,000 narrators before he was even know. 
- They said his memory was photographic


* Narrating to others in different cities, using the knowledge of the isnad 
He was someone know by the uleema and student of knowleadge of his time. For example, he would go to basarah and say I will narrate to you a hadith that you have never heard (because he knew that they were from basarah and they haven't heard certain hadith, as it did not reach them.) He will follow the same pattern in other cities, because he know who's in the chain of these narrations, an knows that no one from basarah has me them (the new city) and he will narrate to them to spread the knowleadge that didn't come.

* Tested by other muhaditheen 
- In Samarqand, he was test be 400 muhadith of for seven days, they will mention narration, mixing isnad, and they couldn't find a single mistake.
- In Baghdad, He was tested by 10 each narrating 10 hadith. They change the chain of the narration, and Imaan bukhaari would say I don't know to each of the altered version, then he recited all 100 back in their mistake that they made and then provided them with the correct version.

* His Ibadah
- Finished the Qur'an 40 times in Ramadan and 1 every 3 nights outside of Ramadan 
- He would spend most his wealth on hadith, to the point where he had no wealth, and would only grass. Someone would come with a bag of dirhams and just walk away, this was a dua that was accepted. 
- Before writing a narration he would make dua and preform 2 rakat so that Allah can guild him to that which was correct, he went thought 600,000 chain, just to compile sahih al bukhaari
  
* Dreams 
- He had a dream, he was standing with a fan and he was blowing the dirt away from the prophet (ﷺ), when he asked he teacher, they said he was the one to clear the lies that was attributed to the prophet (ﷺ), his kitab is the most authentic book after the Qur'an
- Some of his student and teacher had a dream that he was walking along the footsteps of the prophet (ﷺ)
- Muhammad ibn Adam saw a dream that the prophet (ﷺ) who was waiting form Imaan bukari, then ibn Adam when to bukhari and found him passed away. They say when He passed away, the entire land spent of misk. A the people started to take the soil of his grave, so they seal his grave to stop this innovation. 

* Trial
Muʿtazilites, the people was saying that the Qur'an was created. Imaan Ahmed had a trail because of this, was imprisoned and flogged, and the policy was finally ended by al-Mutawakkil

During Imaan Bukhari time, the deviate sect said my words of the Quran, i created (Lafiz Bil Qur'an). The human voice is created and the people didn't know what meant by this, are the speaking about Allah or human word

He went to do a dars in Nīshāpūr, so much people as far as the eye could see, so how did they convey hadith when there was not microphone, he would narrate from 1 side, then back around the around the other side, and if it was the same then he will move to the next hadith.
- Lesson used mustamlis (repeaters), the first ring relayed to the next and so one
  - when the text matched across the circle, did they move to the next narration 

Some people got jealous because of this as they saw everyone is going and no one is coming to their classes. The scholar such as his teacher Muḥammad ibn Yaḥyā al-Dhuhli got jealous and told his student to ask bukhari what is the ruling of the person who recite Qur'an, is own voice created or not? imaan bukahrik said his voice is created, and then they spread this word and said hes a innovator and like the people of mutazilities. Everyone started to boycot, only two people stayed with Imaan Muslim and Ahmed ibn Salama. Imaan Muslim stuck with bukari.

Every land Imaan bukhari went to, he was kicked out. He would live at the outskirt of bukhara and spend his last day by himself. He would ask Allah to take his soul. They say from the pain of his suffering he forgot that he couldn't ask such dua.


* Unique chain per chapter of the same hadith
Imaan Bukhari was also a jurist and this could be seen in his book, where he would have a title of the chapter then the hadith, he would not mention the hadith twice with the same chain. 
