:PROPERTIES:
:ID:       3145ed2e-9fc5-46bd-86e9-e9ad1a9b391f
:END:
#+title: Do not wish to meet the enemy, and ask Allah for safety, but when you face the enemy, be patient, and remember that Paradise is under the shades of swords.
#+filetags: :hadith:

حَدَّثَنَا يُوسُفُ بْنُ مُوسَى، حَدَّثَنَا عَاصِمُ بْنُ يُوسُفَ الْيَرْبُوعِيُّ، حَدَّثَنَا أَبُو إِسْحَاقَ الْفَزَارِيُّ، عَنْ مُوسَى بْنِ عُقْبَةَ، قَالَ حَدَّثَنِي سَالِمٌ أَبُو النَّضْرِ، مَوْلَى عُمَرَ بْنِ عُبَيْدِ اللَّهِ كُنْتُ كَاتِبًا لَهُ قَالَ كَتَبَ إِلَيْهِ عَبْدُ اللَّهِ بْنُ أَبِي أَوْفَى حِينَ خَرَجَ إِلَى الْحَرُورِيَّةِ فَقَرَأْتُهُ فَإِذَا فِيهِ إِنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم فِي بَعْضِ أَيَّامِهِ الَّتِي لَقِيَ فِيهَا الْعَدُوَّ انْتَظَرَ حَتَّى مَالَتِ الشَّمْسُ‏.‏ ثُمَّ قَامَ فِي النَّاسِ فَقَالَ ‏"‏ أَيُّهَا النَّاسُ لاَ تَمَنَّوْا لِقَاءَ الْعَدُوِّ وَسَلُوا اللَّهَ الْعَافِيَةَ، فَإِذَا لَقِيتُمُوهُمْ فَاصْبِرُوا وَاعْلَمُوا أَنَّ الْجَنَّةَ تَحْتَ ظِلاَلِ السُّيُوفِ ـ ثُمَّ قَالَ ـ اللَّهُمَّ مُنْزِلَ الْكِتَابِ وَمُجْرِيَ السَّحَابِ وَهَازِمَ الأَحْزَابِ اهْزِمْهُمْ وَانْصُرْنَا عَلَيْهِمْ ‏"‏‏.‏ وَقَالَ مُوسَى بْنُ عُقْبَةَ حَدَّثَنِي سَالِم أَبُو النَّضْرِ كُنْتُ كَاتِبًا لِعُمَرَ بْنِ عُبَيْدِ اللَّهِ فَأَتَاهُ كِتَابُ عَبْدِ اللَّهِ بْنِ أَبِي أَوْفَى ـ رضى الله عنهما أَنَّ رَسُولَ اللَّهِ صلى الله عليه وسلم قَالَ ‏"‏ لاَ تَمَنَّوْا لِقَاءَ الْعَدُو ‏"‏‏.‏

Narrated [[id:d1d6312e-ba11-4922-b44c-2cb0eadaa49d][Salim Abu An-Nadr]]: 
(the freed slave of 'Umar bin 'Ubaidullah) I was Umar's clerk. Once Abdullah bin Abi Aufa wrote a letter to 'Umar when he proceeded to Al-Haruriya. I read in it that Allah's Messenger (ﷺ) in one of his military expeditions against the enemy, waited till the sun declined and then he got up amongst the people saying, "O people! Do not wish to meet the enemy, and ask Allah for safety, but when you face the enemy, be patient, and remember that Paradise is under the shades of swords." Then he said, "O Allah, the Revealer of the Holy Book, and the Mover of the clouds and the Defeater of the clans, defeat them, and grant us victory over them."

Sahih al-Bukhari 3024, 3025
https://sunnah.com/bukhari:3024
