:PROPERTIES:
:ID:       4742ecab-56cb-4b9a-b37a-a590dacfac3b
:END:
#+title: The Troops (39:3)
#+filetags: :quran:
The Troops (39:3) 

أَلَا لِلَّهِ ٱلدِّينُ ٱلْخَالِصُ ۚ وَٱلَّذِينَ ٱتَّخَذُوا۟ مِن دُونِهِۦٓ أَوْلِيَآءَ مَا نَعْبُدُهُمْ إِلَّا لِيُقَرِّبُونَآ إِلَى ٱللَّهِ زُلْفَىٰٓ إِنَّ ٱللَّهَ يَحْكُمُ بَيْنَهُمْ فِى مَا هُمْ فِيهِ يَخْتَلِفُونَ ۗ إِنَّ ٱللَّهَ لَا يَهْدِى مَنْ هُوَ كَـٰذِبٌۭ كَفَّارٌۭ ٣

Indeed, sincere devotion is due ˹only˺ to Allah. As for those who take other lords besides Him, ˹saying,˺ “We worship them only so they may bring us closer to Allah,” surely Allah will judge between all regarding what they differed about. Allah certainly does not guide whoever persists in lying and disbelief.
— Dr. Mustafa Khattab, The Clear Quran


Unquestionably, for Allāh is the pure religion. And those who take protectors besides Him [say], "We only worship them that they may bring us nearer to Allāh in position." Indeed, Allāh will judge between them concerning that over which they differ. Indeed, Allāh does not guide he who is a liar and [confirmed] disbeliever.
— Saheeh International


true devotion is due to God alone. [As for] those who choose other protectors beside Him, saying, ‘We only worship them because they bring us nearer to God,’ God Himself will judge between them regarding their differences. God does not guide any ungrateful liar.
— M.A.S. Abdel Haleem



https://quran.com/39/3
