:PROPERTIES:
:ID:       18b3ad1e-8b3e-4e19-b5cc-e6a581593ecc
:END:
#+title: Al-Bukhaari
#+filetags: :Imaam:

* Bio
*Name*: Imaan Abū ‘Abd Allāh Muḥammad ibn Ismā‘īl ibn Ibrāhīm ibn al-Mughīrah ibn Bardizbah al-Ju‘fī al-Bukhārī
*Born*: 194AH
*Died*: 256AH
*Age*: 62 
*Titles*: Amīr al‑Muʾminīn fī al‑Ḥadīth (Leader of the Faithful in ḥadīth)

* Teachers
he meet [[id:548d27b9-95e7-45d5-9684-fd68f2e9b526][malik]], Abullah ibn Mubarak and ibn zayd

* Students
Iman Muslim, Timridi, Yusfu al-firabri

* His father was a pious man
His father, Ismael, was known for piety and scrupulous earnings. Reports mention he said he did not know of any unlawful coin in his wealth. He died when al‑Bukhārī was young.

* Complete blind when he was young
his mother say a dream and Ibrahim coming and saying Allah (ﷻ) has return his eyesight 
his mother used to make allot of dua for this, and when she woke up to see Bukhaari and see that the dream it was true

* He stood out in memory and understanding
Memorised Qur'an at 7, He memorised narrations, he went of the lesson of the senion teacher ad-Dakhili, he was narrating hadith of abu al-zubayr, at the time and raised his hand and said you did not narrate from Ibrahim al-Nakha'i. Imaan Bukhaari said go back to your book and check, he went back to his book and he made the mistake and ask him to correct him every time he made a mistake. 

* Al-Tarikh Al-Kabir 
He memories everything about the narrator and compiles the book at the age of 18. He went for Ummrah and stay in Medina, he sat at the rawdah and he would sit the in the full night to write tariq al kabir, it printed in 21 volumes he write all the biography of the narrators with details, (birth/death, reliability and kunays).
- there was many stories in so he remove it to some, out of fear it will become too large.

  
he went ot the leader and said should i show you magic, and in this kitab he writen the bib of 40,000 narrators before he was even know to have writing a book like this
they said his mem of photograpic
and was osmeone who was know at the ulemena and stsudnet of knowledge of his time
he would go to basra and i will narrate to yo hadith that you never headre of and then he would go to another city based on the chain that he know and he know this becase of the cain
and he will memetion them to spread the knowleadge that didnt come

he was test be 400 mudaith of sabar kum, they will mention narration to him and found never a mistak e
another 10 same to narraate 100, 10 eadch and they chane the chain of the narration, they narrate these 100 and is memeories it, then he repeast everything that they said in the same way they narrate it, and then he said the correct version is this. then thhey know this is someone who was choosen to be the leader of the people of hadith
he travel to different land and learning about the hadith
hi was givben the title of the leader of the people of haith
al mizi said imaan bukara he want to gain hadith from all of the muahdith of the town, the muahdithin of the town will come to vist him
he studies under ahmen ishaq al bashar from the senior teacher
kuran has never product someone like hukarai 


time 09:05 for the recording
