:PROPERTIES:
:ID:       2ea5952e-b0cf-4bf1-8187-a671e5f35b90
:END:
#+title: 3. Whoever obeys the Messenger (i.e Muhammad phub) and singles Allah out (in Worship), it is not permissible for him to take allies those who oppose Allah and His messenger, not even if they are close relatives

The proof of this is in:
 #+begin_quote
  [[id:fabc6dd3-15fb-40ff-a413-75766912ae0f][The Pleading Woman (58:22)]]
  You will not find a people who believe in Allāh and the Last Day having affection for those who *oppose Allāh and His Messenger*, even if they were their fathers or their sons or their brothers or their kindred. Those - He has *decreed within their hearts faith* and *supported them with spirit from Him*. And We will *admit them to gardens* beneath which rivers flow, wherein they abide eternally. *Allāh is pleased with them*, and *they are pleased with Him* - those are the party of Allāh. Unquestionably, *the party of Allāh* - *they are the successful*.
  — Saheeh International
  https://quran.com/58/22
 #+end_quote
* Nuh son is not form his family due to his disobedience
:PROPERTIES:
:ID:       3f2548ea-d754-4008-a356-cee265ffa3ec
:END:
when nuh son was dying in front of him and he said not he will go to the mountains, nuh said forgive my son he is from my family, Allah said he is not from you're family

 #+begin_quote
  [[id:65854f15-70fb-438c-aeb2-75534d2410f6][Hud (11:42)]]  
  And it sailed with them through waves like mountains, and Noah called to his son who was apart [from them], "O my son, come aboard with us and be not with the disbelievers."
 #+end_quote

 #+begin_quote
  [[id:e3ab1001-0f4e-46f4-85e0-17d3e0d4e2d8][Hud (11:43)]]
  [But] he said, "I will take refuge on a mountain to protect me from the water." [Noah] said, "There is no protector today from the decree of Allāh, except for whom He gives mercy." And the waves came between them, and he was among the drowned.
 #+end_quote

 #+begin_quote
  [[id:21618d8c-9108-4311-a6c2-b13b777c67d0][Hud (11:44)]]
  And it was said, "O earth, swallow your water, and O sky, withhold [your rain]." And the water subsided, and the matter was accomplished, and it [i.e., the ship] came to rest on the [mountain of] Jūdiyy. And it was said, "Away with the wrongdoing people."
 #+end_quote

 #+begin_quote
  [[id:baf48cbc-0bfb-4c25-a3bb-93fe6ad28235][Hud (11:45)]]
  And Noah called to his Lord and said, "My Lord, indeed my son is of my family; and indeed, Your promise is true; and You are the most just of judges!"
  — Saheeh International
 #+end_quote

 
 #+begin_quote
  [[id:ab3fb205-1445-4d97-9f39-6b338e0051a3][Hud (11:46)]]
  He said, "O Noah, indeed he is not of your family; indeed, he is [one whose] work was other than righteous, so ask Me not for that about which you have no knowledge. Indeed, I advise you, lest you be among the ignorant."
  — Saheeh International
 #+end_quote

 #+begin_quote
  [[id:f790be2e-8aab-42b0-8416-ea67436df9c2][Hud (11:47)]]
  [Noah] said, "My Lord, I seek refuge in You from asking that of which I have no knowledge. And unless You forgive me and have mercy upon me, I will be among the losers."
  — Saheeh International
 #+end_quote

His action is not the action of the righteous, to show that his family is of Islam, Islam take precedence than blood relation, [[id:71bf892f-76b5-4942-8f65-5ae340ba3821][the Ummah is like one body, if any part of the body is in pain, the entire body stay awake due to the pain]]. Everything else is secondary to that.

 
* Al-Wala Wal-Bara
:PROPERTIES:
:ID:       84cd04e2-cb22-4600-b446-b3025a9a881c
:END:
[[id:874b8b0d-7182-4032-80f7-2195b1e27a6a][loving and hating for Allah]]

