:PROPERTIES:
:ID:       498e3db6-9067-49c7-afaa-6865ba61102d
:END:
#+title: Allah is Ar-Rahman Ar-Raheem

[[id:ea3fea39-3797-481e-8b85-0d81a659ab7b][Ar-Rahman]], entirely merciful the one who is describe to have compete mercy 

[[id:69c99aab-6930-44a4-9742-ef4394c534c0][Ar- Rahim]], especially merciful the one who is merciful to his creation 

* [[id:019b1bdf-24b6-4dc9-959f-1e4c362b9587][from his mercy he create 100 branch of mercy]]
From these 100 branch, he as allowed 1 of these branch to down the earth. Form this you’ll see the creations show mercy to each other, and what about the 99, Allah has reserved the 99 branch to the hereafter
- Allah’s *mercy is his attribute*, it an attribute of himself and not a creation.
  - Allah’s attribute of mercy is *not created*, 
    - Allah existed for *eternity*, he is the first and the last,
      - Allah has been describe with mercy for eternity and be *describes* as the *merciful* for *eternity*. 
        - The 99 branches of *mercy* in the hereafter, are the example of the created branches of mercy. 
For example, [[id:6fa1e7d3-5238-403b-8056-87c87191f467][what Allah will say to Jannah]], you are my mercy and i am mercy to you and merciful through you to whoever i want.
- This is an example of 1 branch and we have another 98 branches.
  - after the mercy of Jannah, we have the mercy of Ar-Rahman Ar-Rahim, the mercy of the most merciful. 
When we learn about the mercy of Allah, it make us love him more. How merciful is Allah, just from this 1 branch of mercy, we can see all of the effects of mercy. For example the love and mercy shown to a new born child, just from the 1 branch of the created branch.

