:PROPERTIES:
:ID:       00d59959-8db0-48f2-8426-33d95c14be39
:END:
#+title: thalath lesson 4

What is worship

ling to lower and huble one self the the grreater being with humitlity to sumbit to a greater being

technical
a comprehensive word the encompases everything that Allah loves and that which he is pelase with
- from the statement and actiosn
  - the aarent of them and the hidden of them What is worship
    - the apparent is the statement of the tounge
      - prayer, donig hajj
    - the hidden is what the heart testifies
      - belfit in allah the last day the propeht (ﷺ)
        - hope love and fear
        
- when allah comand us with something
  - he command us with something he loves
    - he tell us the reward
      - he tell us that he is pleased with it
        - or explically call it an act of worship

- act of ibadah are also the thigns that he loves


we are the servant of Allah
- our slavry to allah is two types
  - the gerneal types
    - include all the creation everything in the heaven and earht 
  - the specific type
    - the worshipers or slave of the most mercful
      - the one who chooses to worship Allah

The proof of this is Allah’s saying:

> The Believers (23:117)
> 
> 
> وَمَن يَدْعُ مَعَ ٱللَّهِ إِلَـٰهًا ءَاخَرَ لَا بُرْهَـٰنَ لَهُۥ بِهِۦ فَإِنَّمَا حِسَابُهُۥ عِندَ رَبِّهِۦٓ ۚ إِنَّهُۥ لَا يُفْلِحُ ٱلْكَـٰفِرُونَ ١١٧
> 
> And whoever invokes besides Allāh another deity for which he has no proof - then his account is only with his Lord. Indeed, the disbelievers will not succeed.
> — Saheeh International
> 
> https://quran.com/23/117


this is away is talking aobut both the act of worship



- on the day of judgmenet the will trying to blame the leader and say it was theiere fault in the quran
  - they tought they w'ere doing someing good, e.g. the people of noah example
    -  even they tought it was something it was good it will take take them out of the fold of islam
      - this is the same as the peole of the quraish

        
- if we identify wha the kufr of quriah
  
  haidfa asked about evil so he could say away from it

  haidth - dua is the essentse of worship
  another one dua is workship

  
1.due
dua is to ask
e.g ooh Allah grant me wealth vs asking someing give me wealth
- there are 3 condition to ask the creation
  - if they're not any of these condition then it is disbelief
    1. what you are asking is alive
       - e.g asking a grave
         who ever worship mohammed (ﷺ) he has pass away  and who every wroship Allah he is alive an never dies
         - they went to umar to ask dua for rain
         - in the dua he said we used to ask the prophet (ﷺ) to ask for rain, but not we're going thorugh the uncle of the prophet 
         - someone ask the beduin would to the pophet and asking for reaind when is crop died  
         - they asked messenger of Allah (ﷺ) because is dua is the strongest and his ibadahs is the strongest  
         - why didn't umar ask the prophet (ﷺ) after he has passed away, becayuse it is to show that it is shirk
           - so they turn the uncle for him to ask Allah
       - why did the people ask the idol
         - they know the idol can't help them 
           - umar used to laught
             - because they used to worship the dates and eat them after they we're hungry
         - they believed that the spirit of the righteous people will go into the idol, so they can direct the their worship to the spirit.
           - They are dead. They will not hear you're request
             - if they can hear for arguement sake, then they will not be able to respond to you
               - on the day of judgment the people will you worhsipped will disassoiate from you 
               - Ask Allah directly. Make you're entire relgion only for Allah
               
    2. He is present
       - i.e on the phone 
         - if he is not present then how is going to hear you
           - is he all hearing or seeing
             - can he understand all the languages
               - how can Allah make someone a rival of himself
                 
    3. He has the ability
       - i.e asking someone can you please give me the highest rank of jannah and you make it rain, can you resurrect him from the dead
         - the prophet (ﷺ) is not phyiscally alive, but alive in the barzak
           - if the prophet (ﷺ) was alive like the way we're alive then it will be disbeif to keep the prophet (ﷺ) there and obligaotry to remove him from the grave
         - everyone that we was alloudn to do with the prophet (ﷺ) when he was alive we can't do when he was dead
           - e.g asking allah to forigve you
             - so how can something be imaan when he was alive then be kufr when he passed away
               - how did the sahabah throw dirt to burry the prophet (ﷺ), becasue this was from imaan
               - The ruling of when someone is alive and dead is not the same
               - the prophet (ﷺ) is just human being. and he is the greatest of being, but he is not Allah.   
2.fear

  not every acts of fear permissible
  - permissible type
    - natrual fear
      - lion or gun to you're head
        - you're not accoutnable for this 
  - prohibited
    - don't take you out of the fold of islam
      - scared of praying in public
        - shaved the beard out of fear of the creation
          - the left an obligation
            - they are sinful for this
          
  - shirk
    - someone can do only what Alah can do
      - fearing the saint or jin
        - that will do something to you in the grave
          - we should fear them like the way Allah will harm us
            - they will say things like how can you disrespict our said he will come to you when you're dead trying to make you commit shirk
              - this is the fear you fear something like you should fear Allah, these are the rights of Allah
                - this is the fear of submission
                  - they will leave the fold of islam like this 
3.hope
- what type of hope
  - hoping something that only Allah can deliver
    - e.g. forgiveness of the sin
      - the sharia has came to regulate our actions of our  heart limbs and touges
        hadith - correct them for the small action even if they are small
        - a man put his hand up with two finger the prophet (ﷺ) said not put 1 finger
      - ibn abbas if it wasn't for the dog the theives would have came into our house
        - the propeht (ﷺ) class this as the lesser shirk
          - the propeht (ﷺ) if it wasn't for allah then that
            
4.relinacek
- reling on only upon allah if you're true belive
  - who ever relies on allah, allah is sufficent of him
    - what is the technical meaning
      - to tak ethe nessary mean and leave the rest to Allah
        - not taking the means, is not the correct relance
          and nothe the sunnah
          - and will make the peron look foolish
            - relaince mean to take the mean and is encorraged in Islam
              - the medication is the means and the reason is Allah (who relieves)
                - when musa stand infront of the sea, he has to beat the sea with his staff
                  - all taught the meaning of tawakwal
                - maryam had to shake the palm tree
                  - the take the mean s
                - ayub
                  - hit the earht on his foot to get the srping to come out
          - hence hte meaning is i'm going to do what ever i can
            - it becomes shirk when you rely on something else only which Allah can do  and more other than Allah
              - this is what the quriash did
                - thinkig the stone can accept their dua 
5.desire/logning
  - when you have a great hope for something

6.rahbah
  - doing somehting out of fear

7.to do something in the state of submission
  - no one should humble themselve but only to Allah
    - this is the right of Allah
      - what is the right is to manify Allah more than anything
        - You will not find any other relgion that will give his rights of perfection except in Islam
          - The islam that the prophet (ﷺ) came with
8.awe/fear
- khawf is general fear
  - khashyah - the fear that was build upon knowledge 
    - ibn abas 40 hadith anwawiwi
      - propeht (ﷺ) tought some words
        - guard Allah and he will guard you
          - i.e the harm and alalh
            - if you seek help
              - seek from alalh
                - if everyone was to get together they try to harm you will not be about t do antyhign
                  - the pen has been lifted and the shroll is dryed
                    - what does this do in the heart of the child
                      - they manify Allah
9inbah
- to return our heart back to Allah
  - the regest that come to the heart after a sin
  - we cna appolisges to people and this is not hte same
    - the is the regrest from not going into the hell fire
      
10.help
if you ask help only ask allah hadith 
ibn qayim there is a chpater thaat sumerise the quran, surrah fatiha
and there is a verse that summrise this verse, you alone we worship and you alone we ask for help.
this summrise the entire quran
asking for help is worhsip
and Allah has specified this after
11 seeking protectin
- to seek protection that may protected
  - e.g shataan
12 soemthing that already affected you
- to remove the calimity that you are going throught
13sacrifiting
- indeed my scarifiing is only for Allah haidht
- the spilling of blood is act of ibadah
  - if it was done other than allah then it will be shirk
    - hence do not eat that which the name of Allah has not mention it
      - the curse of Allah is upone this perons
        - the hdaith states that he is distanct from the mercy of Allah  
14vow
- to obligate something for youself for a greater being
  - e.g i'm going to make fastin for myself fard for Allah
  - it becomes obligatory to fulfil it 
    - it is prohibited
  
