:PROPERTIES:
:ID:       931175fc-d87d-40b8-8a8e-570c7d93653b
:END:
#+title: Religion of Islam based on evidence
* 5 pillar of Islam, Emaan and Ihsaan (Muraqaba & Mushahada) 
:PROPERTIES:
:ID:       b02f5c9f-0804-415f-b4d8-47af3307934e
:END:
 [[id:91e4be53-1973-4481-be3d-05dce40e0cb3][Mushahada]] - worship Allah as if he could see him, but not be able to see
  #+begin_quote
   None of you will see Allah until you will pass away
  #+end_quote
 From the examples of the creation, when a person is being watch the preform the task at hand better, than if he was not being watched.
 Now working when someone is in person vs using a camera is not the same, and the task at hand will be preformed different, and not at the same quality.
 
 However with ihsaan, is knowing that Allah is always watching and always aware of what you do, the Ever-Living, the Self-Sustaining, free from any deficiency, the One and only Who is possessed of ultimate greatness and the One only Who is exalted in His Essence, and is exalted in His attributes,  with that knowledge you act according to, think according to it, behave according to it. everything you do is according it, knowing that your lord is always watching, this is to be conscious of Allah, then the task that will be performed will be to his best ability
 A sahabah narrated, [[id:61aec9e5-5314-4fa6-bd4b-2c7372ca17dd][there are too many voluntary act, so which act can someone do that will encompassed all of them. That is to constantly remember Allah.]]
 
 If you are in constant remembrance of Allah, then how hard will it be to even come close to the sin, how can a person sin while remember his lord, how can you fall into evil deeds when you’re doing the good deed known that Allah is watch you. Like when you’re are saying Allah hu akbar, you remember how weak and deficient you are. As Allah [[id:076b0d9a-dc90-40e4-8f60-5752c8678003][say’s you will not pierce trough this earth and you’re not going to reach the mountain in height]]
 - Where does arrogance come from, how can you be proud, when you beginning was a droplet of fluid, while you’re alive you holding impurities in your stomach, when you die, you will turn into a rotten corpse that people will despise because of the pungent foul smell.
 - You’re beginning, middle and ending is despised, so where had this arrogance come from. So the slave of Allah, will say Allah hu Akbar, recognizing that Allah is the greatest and how weak we are and in need of Allah constantly. It make him repent to Allah and lead him to more good deeds. 
 - So he keeps his tongue moist with the remembrance of Allah, what does it do? It encompasses the entire sharia of Allah, as it lead us to every path of goodness and away from harm and evil. 
So this is the religion of Allah, learn about it and perfect it (statement, action, beliefs); to become like the Prophet peace and blessing be upon him,
 #+begin_quote
  [[id:b2fef51c-93a4-4141-91d2-36c84cb1828b][like when Aisha may Allah be pleased with her said his etiquette are that of the Quran.]]
 #+end_quote
Every good quality you’ll find you’ll find it on him and every evil quality, he is free from it, peace and blessing of Allah be on him. Every act of worship you’ll find him doing it, every act of sin, you’ll find him free from it.

* The certainty of being told vs witnessing
:PROPERTIES:
:ID:       f319dc15-6a70-4b12-b8bc-cbe26341d269
:END:
we will study about Allah, his greatness, his rights and his messenger, we will build the certainty to the highest degree 
  #+begin_quote
   The Rivalry in world increase (102:5-8)
   [[id:30547bd0-fe40-4dee-af9e-ed8192c1bdf3][No! If you only knew with knowledge of certainty..]]
   [[id:344da55d-db52-42fb-9cd9-d3cb4bed0f03][You will surely see the Hellfire.]]
   [[id:2e1d4e80-c58a-420f-8e34-843f8fc33a3b][Then you will surely see it with the eye of certainty.]]
   [[id:cc85cc64-3a53-4680-ac18-9cdfd086d872][Then you will surely be asked that Day about pleasure.]]
     #+end_quote
you see the difference between the knowledge of certainty vs eye of certainty, hence our aim is to *increase our certainty*.
** [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Abdullah Ibn Masoud]], was asked what is emaan, he said emaan is certainty.
When a person is certain, he will not leave the obligation, stay away from haram, do the voluntary act and stay away with that which is disliked 
    

