:PROPERTIES:
:ID:       21618d8c-9108-4311-a6c2-b13b777c67d0
:END:
#+title: Hud (11:44)
#+filetags: :quran:

وَقِيلَ يَـٰٓأَرْضُ ٱبْلَعِى مَآءَكِ وَيَـٰسَمَآءُ أَقْلِعِى وَغِيضَ ٱلْمَآءُ وَقُضِىَ ٱلْأَمْرُ وَٱسْتَوَتْ عَلَى ٱلْجُودِىِّ ۖ وَقِيلَ بُعْدًۭا لِّلْقَوْمِ ٱلظَّـٰلِمِينَ ٤٤

And it was said, “O earth! Swallow up your water. And O  sky! Withhold ˹your rain˺.” The floodwater receded and the decree was carried out. The Ark rested on Mount Judi, and it was said, “Away with the wrongdoing people!”
— Dr. Mustafa Khattab, The Clear Quran


And it was said, "O earth, swallow your water, and O sky, withhold [your rain]." And the water subsided, and the matter was accomplished, and it [i.e., the ship] came to rest on the [mountain of] Jūdiyy. And it was said, "Away with the wrongdoing people."
— Saheeh International


Then it was said, ‘Earth, swallow up your water, and sky, hold back,’ and the water subsided, the command was fulfilled. The Ark settled on Mount Judi, and it was said, ‘Gone are those evildoing people!’
— M.A.S. Abdel Haleem



https://quran.com/11/44


