:PROPERTIES:
:ID:       454a6ff1-e30c-4b01-9898-b69a5efd532e
:END:
#+title: they emptied out the alcohol, immediate as soon as the command came 
#+filetags: :hadith:

حَدَّثَنَا يَعْقُوبُ بْنُ إِبْرَاهِيمَ، حَدَّثَنَا ابْنُ عُلَيَّةَ، حَدَّثَنَا عَبْدُ الْعَزِيزِ بْنُ صُهَيْبٍ، قَالَ قَالَ أَنَسُ بْنُ مَالِكٍ ـ رضى الله عنه ـ مَا كَانَ لَنَا خَمْرٌ غَيْرُ فَضِيخِكُمْ هَذَا الَّذِي تُسَمُّونَهُ الْفَضِيخَ‏.‏ فَإِنِّي لَقَائِمٌ أَسْقِي أَبَا طَلْحَةَ وَفُلاَنًا وَفُلاَنًا إِذْ جَاءَ رَجُلٌ فَقَالَ وَهَلْ بَلَغَكُمُ الْخَبَرُ فَقَالُوا وَمَا ذَاكَ قَالَ حُرِّمَتِ الْخَمْرُ‏.‏ قَالُوا أَهْرِقْ هَذِهِ الْقِلاَلَ يَا أَنَسُ‏.‏ قَالَ فَمَا سَأَلُوا عَنْهَا وَلاَ رَاجَعُوهَا بَعْدَ خَبَرِ الرَّجُلِ‏.‏

Narrated [[id:685a9a53-941d-46fe-b886-5935bbd43f2a][Anas bin Malik]]: We had no alcoholic drink except that which was produced from dates and which you call Fadikh. While I was standing offering drinks to Abu Talh and so-and-so and so-and-so, a man cam and said, "Has the news reached you? They said, "What is that?" He said. "Alcoholic drinks have been prohibited. They said, "Spill (the contents of these pots, O Anas! "Then they neither asked about it (alcoholic drinks) nor returned it after the news from that man.

Sahih al-Bukhari 4617
https://sunnah.com/bukhari:4617
