:PROPERTIES:
:ID:       a4a32076-1a68-48eb-a904-0c29e17d0977
:END:
#+title: 4. Patience with the harm that befall due to it

* When acquiring the knowledge it not always going to be an easy path
Like for example when the prophet peace and blessing of Allah be on him went to Taif the children threw rocks, and they didn’t accept the message. 

His companions we’re persecuted, for example bilal ra, had a chain around his neck and the children will drag him like he was a dog. He was place on a hot plate in front of the burning sun and he would say my lord is one, my lord is one

Amman ra, saw his parents being killed, some of the was persecuted to the point they wished death upon themselves, then the prophet peace and blessing of Allah be on him heard about this, and said none of you should wish death on himself, but if he comes to this situation, then should make dua to Allah. If life is good for me give me life, and if death is good for me, then give me death. This is what they we’re going through. 

The prophet peace and blessing of Allah be upon him, was attacked numerous times by the quraish and other than them, the patient that the person much have on this path, can only come by the help of Allah to allow them to be successful with it. 


* Imaan [[id:18b3ad1e-8b3e-4e19-b5cc-e6a581593ecc][bukaari,]] used to eat grass because he had no food when travelling to learn,
:PROPERTIES:
:ID:       327e2894-6944-4ed8-8e07-645d29c25dcd
:END:
scholars used to travels for months,
- anyone who take this path they will face trials when acting according to this knowledge.
- sometime the people will not accept the knowledge you have, they may harm you or frame your and it may cause you hardship.


* 3 types of patients
:PROPERTIES:
:ID:       13ecd11e-e4fb-4d6c-8c13-868b07d0dcbd
:END:
** 1. patient when it comes to the obedience of Allah 
:PROPERTIES:
:ID:       fcbf2af5-6344-4aec-b440-ddabdc977852
:END:
** 2. patient when stay away from sin
:PROPERTIES:
:ID:       7c756d5a-f313-419e-92fe-5dc30307fb27
:END:
- remind you’re self that what is in the hereafter is better
The scholars used to say whoever leaves something for the sake of Allah, then Allah will replace it with something good/better than it, some say it’s a hadith, some say it’s not attributed to the prophet peace and blessing of Allah be on him, but the meaning is valid
*** some Sahabah used to fall on the floor from being drunk, then the prohibition came
:PROPERTIES:
:ID:       a70694d5-55b8-4596-8cad-4c201939b1f5
:END:
 #+begin_quote
  [[id:0fd3c0a8-e9d6-4fa7-94a9-c989c2a682ad][The Table Spread (5:90)]] 
  O you who have believed, indeed, intoxicants, gambling, [sacrificing on] stone alters [to other than Allāh], and divining arrows are but defilement from the work of Satan, so avoid it that you may be successful.
  — Saheeh International
 #+end_quote
**** When this prohibition came, the streets of Medina became flowing with alcohol, [[id:454a6ff1-e30c-4b01-9898-b69a5efd532e][they emptied out the alcohol, immediate as soon as the command came]]

** 3. patient when it comes to the decreed of Allah 
:PROPERTIES:
:ID:       9fd0b713-5781-40ca-90de-a0add180c964
:END:
*** Trials, Patience, and Expiation of Sins
:PROPERTIES:
:ID:       a78bac1c-d41c-4a38-8ad7-1a413b2e34db
:END:
The prophet peace and blessing of Allah be on him said, [[id:bf20b693-3f2b-48bd-89f9-b7d55218ef25][nothing hit the believe, except it expiate the sin of the believe]], [[id:e7f2149b-1582-47b1-8e6b-3b3bdf16fcad][every calamity is a blessing]] 

Some of the early scholars, [[id:b88ead40-410e-4c16-a7ea-3370dabe5a57][if they haven’t been inflect with illness, they will being to cry, they would think does that mean that Allah no longer loves me,]] don’t want to cleanse my sins, as [[id:ab5191db-729d-4ebf-9d86-d57be76e8f94][sickness is expiation for sins]].

[[id:a2460935-6191-4a1b-8ee7-3f533cb944dd][The greatest reward comes with the greatest trial. When Allah loves a people He tests them. Whoever accepts that wins His pleasure but whoever is discontent with that earns His wrath.]]


 #+begin_quote
  [[id:58a6d260-027a-4917-8ab3-e25eb60cf2e1][The Cow (2:155)]]
  And We will surely test you with something of fear and hunger and a loss of wealth and lives and fruits, but give good tidings to the patient,
  — Saheeh International
  https://quran.com/2/155
 #+end_quote
*** The Prophet ﷺ final illness
:PROPERTIES:
:ID:       3f53355b-6e5f-4092-a00e-c96209e779a0
:END:
look at the prophet peace and blessing of Allah be upon him, he become so ill that Aisha ra, describe he was lying on his bed, he will fall unconcious and when he came back he would ask for cold [[id:41d226d6-09e3-41b8-9c6e-aab4d56d4921][water to be pour onto the body, because of the heat that he was feeling.]]

He peace and blessing of Allah, was ill to the point he couldn't lead the Salah, so [[id:eb36ad42-d1b5-4adf-91ab-bcd019b0a5d4][he appointed Abu Bakr to lead the pryaers]], toward the end of his life aisha said that the prophet peace and blessing of Allah be on him, used to [[id:c09a3c57-9f6c-4699-82b1-b9beed484814][pray the night prayer sitting down]], but it’s not sunnah to pray the night prayer sitting down, but he peace and blessing upon him didn’t allow it to leave the night prayer.
*** Heaviness of revelation
:PROPERTIES:
:ID:       4728a6df-8829-4e77-88d6-fd9a97bc947d
:END:
Even when receiving the revilation, aisha RA would say that on [[id:a0f0b312-559d-4dd5-b8d9-c08eb8b4b86a][a very cold day and noticed the sweat dropping from his forehead]] from [[id:17aa6a07-0350-4ea3-9f26-96e589cfeda4][The heaviness of the revilation]].

*** He ﷺ buried (most of) his children; he wept over his son and grandchild
:PROPERTIES:
:ID:       ad4db997-f0ad-4514-8408-ab40d47257d3
:END:
Allah loves him more than us. He buried his children his own and, all them passed away in his life time except Fatima, and even buried some of his grandchildren, peace and blessing of Allah be on him.

[[id:eb95e862-4939-403c-a9c2-75c9a92e6d29][Like his daughter send a messenger, send a message to the prophet peace and blessing of Allah be on him, said my child is about to pass away,]]be he peace and blessing of Allah be on him was dealing with the affairs of the ummah during the time and sends a messenger for her, and see asked again to come. He lifted his grandchild, and the child start to shake and the prophet peace and blessing of Allah be on him, started to cry, and the companions we’re surprise and asked what is this, the prophet said this is mercy that Allah has put in the heart. It is permissible to cry, but not to wail, like jahilayah, like people used to [[id:ffdb35fe-4a12-4939-bb0c-4aea7c7c278a][tear their clothes and hit their cheeks]]. 
    
In another narration, the prophet peace and blessing of Allah said:
 #+begin_quote
  [[id:164b8738-24d0-4e80-a1d6-d2934f5fba16][Verily, the Messenger of Allah (ﷺ) declared himself free of (the responsibility) for a woman who wails, shaves her head and tears up her clothes.]]" [Al- Bukhari and Muslim].
 #+end_quote
cry in a manner that will preserve you honour 
    
*** Jihad is a hard but beloved ruling (loving Allah’s commands despite hardship) 
:PROPERTIES:
:ID:       c6f923c6-6113-4201-8292-480714365ba1
:END:
- another example of patients, is when the sahabah, was told about jihad,
- they love the ruling of Allah, because there is only good in it, but the hardship, is what they found difficult.
Example in the Quran fighting has been prescribed for you even if you dislike it.
 #+begin_quote
  [[id:36d2f934-7fe3-4f9e-92bd-28f1b3000059][The Cow (2:216)]]
  Battle has been enjoined upon you while it is hateful to you. But perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allāh knows, while you know not.
  — Saheeh International
 #+end_quote
In a narrations it says: [[id:3145ed2e-9fc5-46bd-86e9-e9ad1a9b391f][Do not wish to meet the enemy, and ask Allah for safety, but when you face the enemy, be patient, and remember that Paradise is under the shades of swords.]] And in another narrations, [[id:02db769a-7006-4dbe-82ef-b7f0e4efd78d][Paradise is under the shades of the sword]]. 
    
like the cold morning to wake up for fajr and cold water and going to the masjid when it’s snowing

to have patience is to show obedience
