:PROPERTIES:
:ID:       c3382935-f014-40ac-9afc-4d0d53ca6b5c
:END:
#+title: say I don’t know
   
* Imaan [[id:548d27b9-95e7-45d5-9684-fd68f2e9b526][Malik]] (may Allah have mercy on him) used to say:

** “Whoever is asked about a matter,
*** before answering, he should examine himself in terms of Paradise and Hell, and how he will be saved in the Hereafter, and then answer.”
:PROPERTIES:
:ID:       6b8823ad-abaa-4488-838d-ff76eaf96642
:END:
*** He was asked about a matter, and he said: “I do not know.”
:PROPERTIES:
:ID:       6ee3df13-b5ef-4c14-a3e2-f315cff45e64
:END:
*** It was said to him: “It is a light and easy matter.”
*** He became angry and said: “There is nothing light in knowledge. Haven’t you heard the saying of Allah the Almighty? 
*** All knowledge is weighty, especially what you will be asked about on the Day of Resurrection.” He said: “I did not give a fatwa until seventy people testified that I was worthy of it.”
*** He also said: “It is not appropriate for a man to consider himself worthy of something until he asks someone who is more knowledgeable than him. I did not give a fatwa until I asked Rabi’ah and Yahya ibn Sa’id , and they ordered me to do so. If they had forbidden me, I would have stopped.” 
*** He said: “If the companions of the Messenger of Allah (blessings and peace of Allah be upon him) found matters difficult, and none of them would answer a question until they consulted the opinion of their companion, despite the guidance, success, and purity that they had been given, then how about us, whose hearts are covered with sins and transgressions?” When he (blessings and peace of Allah be upon him) was asked about a matter, it was as if he was standing between Paradise and Hell.
       
        
عن عَبْد الرَّحْمَنِ بْن مَهْدِيٍّ قَالَ كُنَّا عِنْدَ مَالِكِ بْنِ أَنَسٍ رحمه الله فَجَاءَهُ رَجُلٌ فَقَالَ يَا أَبَا عَبْدِ اللَّهِ جِئْتُكَ مِ/نْ مَسِيرَةِ سِتَّةِ أَشْهُرٍ حَمَّلَنِي أَهْلُ بَلَدِي مَسْأَلَةً أَسْأَلُكَ عَنْهَا قَالَ فَسَلْ فَسَأَلَهُ الرَّجُلُ عَنْ مَسْأَلَةٍ فَقَالَ لَا أُحْسِنُهَا فَبُهِتَ الرَّجُلُ كَأَنَّهُ قَدْ جَاءَ إِلَى مَنْ يَعْلَمُ كُلَّ شَيْءٍ فَقَالَ فَأَيُّ شَيْءٍ أَقُولُ لِأَهْلِ بَلَدِتِي إِذَا رَجَعْتُ لَهُمْ قَالَ تَقُولُ لَهُمْ قَالَ مَالِكٌ لَا أُحْسِنُ
قَالَ ابْنُ وَهْبٍ وَكُنْتُ أَسْمَعُهُ كَثِيرًا مَا يَقُولُ لَا أَدْرِي
2/838 جامع بيان العلم وفضله
         
Abdur Rahman ibn Mahdi reported: I was with Malik ibn Anas, may Allah have mercy on him, as a
** man came and he said,
:PROPERTIES:
:ID:       b7ecfcc8-0840-416b-8859-e95078983548
:END:
*** “O Abu Abdullah, I have come from a distance of six months travel. The people of my land have an issue to ask you about.”
:PROPERTIES:
:ID:       b26410f9-a58a-42bf-8766-e452061ef535
:END:
Malik said, “Then ask.” The man asked him about the issue and Malik said, “I do not know it.” The man was speechless, as if he had thought he came to someone who knew everything. The man said, “So what do I say to my people when I return to them?” Malik said, “Say to them that Malik said: I do not know.”
**** Ibn Wahb said, “I heard him many times saying: I do not know.”
:PROPERTIES:
:ID:       97a9eace-325c-4e54-b366-d1687a3f5ae0
:END:
Source: Jāmi’ Bayān al-‘Ilm 2/838
          

