:PROPERTIES:
:ID:       3a317c6a-513a-48cd-a8aa-c2f062d9c3b1
:END:
#+title: 2. Acting on this

Knowledge Demands Action (The Qur’an as Witness, Uphold Tawheed and Guard Against Shirk)

* Whatever you learn you must act upon it.
:PROPERTIES:
:ID:       70b4075e-4db2-4c51-9fce-ea9ee8b2e0c4
:END:
- The prophet peace and blessing be upon him stated that the [[id:52bb32ac-82d3-42a5-8572-179abd2213fa][quran will be a proof for you or against you]], [[id:624932ac-f478-4aed-aef2-16d9cf49150c][it will say oh Allah this person recited me]] and [[id:b132da93-1b6e-4ef1-9bb3-856e0343df0a][acted upon me]] or it could say that this person didn’t act upon
  
* The Rights of Allah, fearing shirk
:PROPERTIES:
:ID:       049f8a0f-4cbd-47c0-8d92-95c516fdf612
:END:
After learning about the oneness of Allah, how can we associate partner with Allah, when he is the only one deserving of worship.

Today we find people asking graves, stones, tree and everything else other than Allah. 
How can this happen when the Quran is clear, yet
** Shaytaan knows how to attack the humans.
:PROPERTIES:
:ID:       b5388b5c-ba15-4f4f-b24d-260e27619c0f
:END:
As he says:
 #+begin_quote
  [[id:5acf8ac6-81dd-4154-867f-72b05c945c11][The Heights (7:17)]]
  Then I will come to them from before them and from behind them and on their right and on their left, and You will not find most of them grateful [to You]."
  — Saheeh International
  https://quran.com/7/17
 #+end_quote
*** Ibrahim AS, who is the greatest prophet after, Muhammed peace and blessing of Allah be on him,
:PROPERTIES:
:ID:       7f00ee5f-38ef-44e3-9f41-31b3cbe8f430
:END:
  *** Allah described him as [[id:594849aa-6d6a-4341-8185-bcd1fdecbcc4][the leader of the people of tawheed]], as a nation 
   - Even he was scared that shytaan would make him commit shirk, so he made a [[id:3572cc29-96aa-48be-b02e-fd4acda76bc3][dua to stay away from it]] 
   - It wouldn’t cross our mind that he would need to make such a dua, because he’s the imaan of the people of tawheed.
     - It show’s us how shytaan is going to come.
   - When we act, we act upon tawheed we study, we love, the prophet peace and blessing be upon him, so we follow his guidance, we love Islam and we implement everything from it

* The believes acquire knowledge and act upon it, these are the people that Allah chose to favour the ones that act on knowledge
:PROPERTIES:
:ID:       2616b067-b73a-45f3-aeac-e72f9a8bc83a
:END:
- not like the one who earned Allah’s anger, they are the ones who knew, but did not act on it like the jew
- not like the misguided ones, they act without knowledge, like the Christians
