:PROPERTIES:
:ID:       9b0d0294-7f07-40ee-98f0-4d0f8b2c313f
:END:
#+title: Had Allah not send down a proof to his creation other than this surah, it would have been sufficient for them
quoted from [[id:2dada820-43bc-4ab9-a532-d10230524921][Ash-Shaafi’ee]] statements
-----
The evidence for All these 4 points 

* [[id:0bcbac22-28a7-44cc-a51e-1f9f3fc22eb1][Allah]] means the one who is deserving to be worshipped
it encompasses all the meaning of every other names of Allah. It is the greatest name of Allah. 

why Allah encompasses these other names, like Ar-Rahman, because Allah is completely perfect and is deserving of worship. He has to be the Lord, the sustainer, the completely merciful, does not sleep or slumber, if he wasn’t these things, then he would not be deserving of worship.    

- for example the Christian that worship Esa, they used to eat food and are dependent on things, so how can a thing that is depending on something else be worshipped
  
- musailama called himself ar-rahman, an now he is know as the liar. 

* Allah swears by time
:PROPERTIES:
:ID:       e182c177-9a0b-4eef-b090-a20d5b1c0938
:END:
The prophet peace and blessing of Allah be on him, said [[id:c89270b6-6447-4758-a483-90942fc1b1e1][do not swear by anything other than Allah]], however Allah is the creator of the heaven and the earth.

Allah swears by himself or the creation, when he swear by the creation, it shows the importance of the thing that is being sworn by, for example time, if it wasn’t sworn by it, then it wouldn’t be important

Shaykh al-Islam Ibn Taymiyah (may Allah have mercy on him) said:
 #+begin_quote
 Allah swears by some of His creation because they are His signs and creation, so they are indicative of His Lordship, divinity, oneness, knowledge, might, will, mercy, wisdom, greatness and glory. He, may He be glorified, swears by them because swearing by them involves affirming His greatness, may He be glorified.  But we should not swear by them, as is indicated by the religious texts and scholarly consensus." (Majmoo‘ al-Fataawa  1/290).
 #+end_quote

If Allah swears by something and then mention something, then it means these to thing are connected, [[id:47cc7e3b-0de0-4134-947b-00fdf222b4b6][so why are the people lost? It is because they have not made use of their time]] 

Hasan al basri and other said 
 #+begin_quote
  oooh sons of Adam, you are just a matters of days, every time a day passes a part of you is gone. When a day goes it never comes back again.
 #+end_quote

Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience. You cannot believe without knowledge. Suratul asr is a evidence for these point
