:PROPERTIES:
:ID:       d92dd0be-1068-4b8b-8aff-b402fd780296
:END:
#+title: break of dawn.

Just before Fajr

Many early sources report a miraculous light associated with the Prophet’s birth.

In Musnad Ahmad, from al-‘Irbad ibn Sāriyah, the Prophet ﷺ said his mother saw at his delivery a light that illuminated the palaces of Syria; Ibn Hibban and al-Hakim graded it Sahih, and al-Haythami called its chain ḥasan. Other narrations (Ibn Hishām, al-Ṭabarī, al-Ṭabarānī) describe a dream-vision during pregnancy and a light that filled the house at birth. Ibn Kathīr reconciles them by saying she dreamed it while pregnant and then saw it realized with her eyes at delivery

Ibn Hajar said in Fat'h Al-Baari:

“Among the signs of his Prophecy that appeared at his birth (ﷺ) and after his birth was what At-Tabaraani narrated from 'Uthmaan ibn Abi Al-‘Aas Ath-Thaqafi, from his mother, that she went to Aaminah, the mother of the Prophet (ﷺ) and she related that when she [Aaminah] was in labor (i.e. giving birth), ‘I was looking at the stars getting closer to me to the point that I thought they would fall on me; and when she gave birth, a light came out of her that lit the whole house.’”

This hadeeth is supported by another hadeeth narrated by Al-Irbaadh ibn Saariyah, who said:

“I heard the Prophet (ﷺ)  say, ‘(Allah has written in the Preserved book) that I am the Slave of Allah and the Seal of the Prophets while Adam was not yet created. I will inform you about that: I am (the result of) the supplication of my father Ibraaheem (Abraham), the glad tiding given about me by ‘Eesa (Jesus), and the vision which my mother saw – like what all the mothers of Prophets see – and that when the mother of the Prophet (ﷺ) gave birth to him, she saw a light that lit up the palaces of the Levant.” [Ahmad - Ibn Hibbaan and Al-Haakim graded it saheeh (sound)]
