:PROPERTIES:
:ID:       e3a4b4e0-4dda-4711-ac83-3436e0be43bc
:END:
#+title: The Hundred Line Poem Recounting The Life Of The Most Noble of All Creation

by [[id:a5061071-f5a6-4c40-849f-c20b496c15fd][Sheikh ibn Abil-'izz al-Hanafi]] (d. 792AH), who summarised ibn Kathir book in a poem.

* Why we're studying this?
[[id:32fd93d7-c48c-4251-8f1c-4a0f4de38e6e][It is a right he (ﷺ) has we love him (ﷺ) peace and blessing of Allah be on him, more than ourselves, our parents, children, all of mankind.]] Hence the reason why we should learn this Kitab, is to learn who the Prophet (ﷺ) is and this will increase your love for the Prophet (ﷺ), you'll say (ﷺ) not out of obligation, but with love.
 

* 1. [[id:593cd4a4-1a17-41c6-bfe3-70bc06ad0f8b][All praise is for Allah]] (ﷻ), The Eternal, The Maker; followed by his salah upon [[id:884f4fe3-5285-46ed-8a7c-c6723514bd34][the chosen one (ﷺ)]].
:PROPERTIES:
:ID:       5a7b1223-fd68-4dab-9fec-608e34e61831
:END:
* 2. Here is the [[id:c74ce59c-44ec-4d71-ae4e-5dc79028fc4a][Messenger's biography]]; in [[id:ea247e91-db78-4607-9e21-c839e4f9091d][poem]] form with succinct sections. 
:PROPERTIES:
:ID:       1298b57f-721f-4a99-912d-2387a26de16b
:END:
* 3. His birth was on the [[id:bd4b022c-9634-4078-908f-a4aa7c45a7eb][tenth of the distinguished month]]; [[id:66f4ca09-ad56-4356-8a13-b7dd7a114489][Rabee' al-Awwal]], in the [[id:21b0904f-50a0-48bd-9172-45a0da6db39c][year of the elephant.]]
:PROPERTIES:
:ID:       a7d889c9-dcc7-4f75-95ae-767e4f0152bd
:END:
* 4. However, the [[id:fd77c009-9dd2-47c0-8cf1-6dd85ca9d898][common view is that it was the twelfth on a Monday]] at the [[id:d92dd0be-1068-4b8b-8aff-b402fd780296][break of dawn.]]
:PROPERTIES:
:ID:       f6539d10-9ecc-4a07-8776-abc98543afab
:END:
* 5. Corresponding to the twentieth of April. Prior to that his [[id:8545ea5d-8bed-4cb1-876b-7e6717816106][father passed away.]]
:PROPERTIES:
:ID:       94522553-9d95-495e-a0d2-5a32b8f68c5c
:END:
 6. Two year later he was weaned and bought back safe an sound by his wet-nurse.
   
 7. Haleemah, to his mother, she then returned with him to her own family as she had desired.
 8. Two moth later his belly was cleaved open, though some say it was when he was four year old.
 9. At six years and one month, while returning his mother passed away at al-Abwaa'.
 10. And his paternal grandfather, 'Adul-Muttalib, passed away while he was eight, no lie.
 11. Then his paternal uncle, Abu Talib, took on his guardianship, and later to ash-Shaam he travelled. 
 12. That was while he was twelve years old and the well-know incident with Baheera took place.
 13. The best of mankind again travelled to ash-Shaam at the age of twenty five - remember it.
 14. As a trader for our other, Khadeejah, and he returned that year after profgibe trade, happy.
 15. In that year his marriage to her and he later consummated his marriage with her.
 16. All his children were from her except ibraaheem The first to earn that distinction was al Qaasim.
 17. Then came Zaynah, Ruqayyah, Fatimah, and Umm Kultoom, who was the last of the girls.
 18. And at-Taahir, at-Tayyib, 'Abdullah; but some say each name belonged to a separate beautiful child.
 19. All of them tasted death during his lifetime, except Fatimah who died half a year after him.
 20. At thirty five he participated in rebuilding the house of Allah after it dilapidation 
 21. They appointed him to arbitrate and accepted his solution for putting the black stone into place.
 22. At the age of forty he was sent as a messenger; on a Monday with certainty - so convey it.
 23. During ramadaan or Rabee' al-Awwal, and Surah Iqra was the first of the revelation.
 24. Then wudo and salah, he was taught by Jibreel, as two complete units of prayers.
 25. then after the passing of twenty full days, enormous, terrifying stars pelted the jinn.
 26. then in the Fourth year, he called openly to Islam as commanded.
 27. four women along with twelve men among the companions all migrated
 28. to the lands of habashah in the fifth year. the same year, they returned, but went back without blame
 29. they were eighty three men accompained by a group completing their total number;
 30. and they were eighteeen women. later on, in the sizth year, hamaz al asad accepted islaam
 31. Nine year after his prophethood came the death of abu talib, his guardian;
 32. follwed by khadeejah who passed away after three days had elpased. 
 33. After fifty and a quater years, islam was embraced by the jinn of naseebeen, who then departed - let it be known
 34. Thereafter, he maried Sawdah in ramadaan , followed by 
 35. hi marriage to the dought of as-sideeq in shawwaal. at the age of fifty one
 36. he was taken by night and the alawaat were obligated ; fixe with the reward of fifty, as authetnetically preserved 
 37. The first bay'ah was with twelve of the people of taybah, as he been mention. 
 38. At the age of fifty two came seventiy in the hajj session  - and this is confimed 
 39. from taybah, the pledge allegiance, and he later left makkah on a Monaday in the moth of safar
 40. Thus, the one contented arravied in yabah, for certain thaving reached the age of fifty three 
 41. On a monday. He remained here for ten full years as we shall recount
 42. in the first, year salah of a residen was made complete, this wqas agter prayed jumu'ah - listen to my words 
 43. He then contructed a masjid at Qubaa' , as well as the majid in the noble city, al-Madeenah 
 44. Then, around it, he built his dwellings . Later this year arrived 
 45. less than half of those who have travelled to the land of habadhah when they migrated. 
 46. in the sma year, the noblest of all elete establsihed tie of brotherhood between the jmuhaajireen and ansaar 
 47. He then consummated marraige with the doughter of his best companion, and legislated the athaan, so follow his example
 48. The battle of al-abwaa took place afterwards, in safar. subsequnetly, in the second year, combat spread
 49. to buwaat and then badr. The obligation of redirecting the qiblah come in the middle of rajab
 50. Follwing thill-'ushyr, o my borothers. fasting for a month was obligated in shaa'baan 
 51. and the major clash whcih was at badr happened during fasting, on the seventeenth of the month
 52. zakaah al fitr was obligated in it follwing badr by ten nights 
 53. There is difference regarding zakaah al maal - you must realise this. The daughter of the rightous prophet passed away 
 54. ruqayyah, prior to the arm's return; she was the wif of 'Uthmaan. The marrage of the achaste '
 55. Fatimah to the esteemed ali and a al-abbas accepted islam after being taken captive
 56. And as for Qaynuqaa', Battle with them ensure afterwards. And he sacrifed on the 'Eid of Slaughter.
 57. And the attle of as-aweeq, then Qarqarah. And combaste in the thri year spread further 
 58. to ghatafaan and bani sulaym. Umm kulthoom, dughter of the noble esteemed, 
 59. wa married to 'uthmaan and he ened this distinction. And the prophet later married hafsah
 60. and zaynab also; then heaed to uhud for battle - in the month of shawaal - and hamraa ' al asad.
 61. Intoxicants were prohibited undoubtely - so listen - and that year his grandson al-hasan, was born 
 62. In the fourth year, battle reached bani an-Nadeer in Rabee' al-Awwal
 63. The followed the heath of zaynah, the aftermentioned, and tafterward, marraige to umm salamah 
 64. and the doughter of jahsh. Then, to badr as appointed followed by al-ahzaab - so listen and keep count 
 65. then bani quraythah, tough regardin gthese two there is difference. And at-thaat ar-riqaa' he taught 
 66. how to pray salah al khawf; and prayer was shortened, as reported. and the verse about hijaab and tayammum  
 67. some said and his stoning of the two jews, and the birth of his lovely gradson, al husaynm
 68. in the fith eyar- list and trsut me - was the slander during the battle of bani al mustaliq
 69. doomah al jandal happened before that . and also he wed the daughter of al haarith later one and consummated. 
 70. his marriage to rayhaanah was in the fith. Then bani lihyaan was at the beginning of the sixth year 
 71. After that his istisqaa' prayerm, the thoo qarad, and he was obstructed from performing 'umrah as he wished. 
 72. Bay'ah ar-ridwaan came frist, and he consummated that year his marrage with rayhaanah as clarified. 
 73. and Hajj was obligated, trought with differnce - so take heed - and the concquest of kaybaar was in the seventh year.
 74. The meat of domestic donkeys was prohibited that year, as well as the corroup mut'ah form of marriage 
 75. He later married Umm Habeebah and her mahr on his behalf an najaashee paid 
 76. A lamb was poisoned and offered as a gift and he later chose for himself the pure safiyyah 
 77. she xame, as well as all the remaining migrants. and marriage to moaymoonah was the last. 
 78. prior to that was the islam of abu hurayrah and agter was the famous umrah al qadaa
 79. and the envoys in the sancitified month of muharram he them to the kings - so know this 
 80. presented as a gift was mariyah al qibtiyyah that year. then in the eight year was sariyyah
 81. which headed to mu'tah and during gasting the conquest of al-Balad al-Haram took place. 
 82. after it, they relate what happened during the day at hunayn, and then the day at at-ta'if
 83. Later in Thul-Qa'dah, he performed umrah from al-ji'irraanah, and he was settled. 
 84. His daughter, zaynah, passed away and then ibrahim was born in it, surely. 
 85. And turn was given to aisha by sawdah for as long as she remained alive
 86. The mimbar was made and placed conspicoucly, and 'Attab led the people in Hajj
 87. The expedition to tabook was in the nenth year and he demolised masjid ad-diraar, removing it's harm 
 88. abu bakr led the poeple in hajj, and there ali recited "barr'ah" and dicisvely declared
 89. that no mushrik would again perform Hajj, and none unclothed would make tawaaf - they both carried out as instructed 
 90. Delegations came in plenty, one after another and he swore he would not go to his womenfolk for a month
 91. He annonced the headth of an-Najashi and prayer upon him from taybah, earning him great virtue 
 92. Ibrahim passed away in the final year and al-Bajalee accepted islam, and his name was jareer
 93. He performed the Farewell Hajj as a Qaarin and he stopped on a Friday during it in security 
 94. And revealed that day was a glad tiding for you: This day I have perfected for you your relgion.
 95. Rayhaanah's death was after his return and the nine lived on after him.
 96. And on a Monday he finished - for certain - having completed sixty-three. 
 97. He was laid to rest in the dwwelling of the daughter of as-siddeeq at the location of his death, precisely dermined
 98. The duration of his illness was two fifth of a month bu csome say it was a thrid and gigth - know this 
 99. This concluded the hundred line poem recounting th life of the most noble of all creation
 100. May Allah, may Lord, send Salah upone him and upon his companions, his family and those who follow. 




