:PROPERTIES:
:ID:       555a5917-a056-4a45-b474-826991512081
:END:
#+title: nouns
1. Nouns - ‫األسماء‬:
   refer to words that denote a person, place, thing, or abstract concept (ilm).

   In a sentence, nouns are crucial because they are used to:
   - identifying
     - subjects - who's doing
     - objects - who's receiving
     - attributes within a sentence (description)
   - imparts meanings independently without the need to denote time.
     
   Examples include kitab (book), bint (girl), and ilm (knowledge).

   
   You can think about nouns in terms of how wide or narrow their reference is:
     1. general nouns
        general concept or classes of object,
        - such as relative nouns that could apply broadly across many instances.
          - examples: “students”, “people”, “books”.
            - al-insan, all of mankind is a loser
              - this is said in generality
              - e.g genrality of things in the sea being hala to eat
              - everything will die except Allah
            
     2. absolute nouns
        often seen in indefinite (non-specific) forms in affirmative context,
        - these nouns express meaning that are unrestricted or not limited to specific instances
          - e.g. “a slave”, “a believer”, “a book”.
            - express meaning that are not restrict, like free a slave, does he have to be black white male female, no, it is unrestricted
              
     3. specific nouns
        Particular entities or items
        - highlighted through defined article or context, making them distinct and identifiable.
          - “the girl”, “that book”, “Zayd”
            - you are specificly told to do that one thing, e.g. musa to sluaghter a specific cow (upon many resitriction/conditions)
              
     (understanding these element's and their function in speech is fundamental in appreciate how language contract meaning and facilitates communication)


