:PROPERTIES:
:ID:       2ea83203-15c8-4829-9dc1-9411700fb41a
:END:
#+title: 1. That Allah created us, provide sustenance for us, and did not leave us neglected. Rather He sent a Messenger to us. So whoever obeys him will enter Paradise, whereas whoever disobeys him will enter the Hellfire

* The proof of this is Allah statement:
 #+begin_quote
 [[id:6d73ba73-a0b0-4d6f-acac-1fc4afe48e03][The Enshrouded One (73:15)]]
 Indeed, We have sent to you [[id:40773e01-a036-4f5e-8e33-29550c71b625][a Messenger as a witness upon you]] just as We sent to Pharaoh a messenger.
  — Saheeh International
 #+end_quote
 #+begin_quote
 [[id:d7447816-00fd-4f4f-ab23-378a70e947b7][The Enshrouded One (73:16)]]
 But Pharaoh disobeyed the messenger, so We seized him with a ruinous seizure.
  — Saheeh International
  https://quran.com/73/16
 #+end_quote


* Allah created us
:PROPERTIES:
:ID:       55ccd121-b58f-484e-9b04-a19c53d883e9
:END:
Why we should worship Allah?

Allah is completely perfect and is free from imperfection and deficiency. [[id:0bcbac22-28a7-44cc-a51e-1f9f3fc22eb1][Allah]] alone is the Rabb (creator, provider and disposer of affairs), He alone is deserving of our worship and magnification alone (not the stones, tree, nafs or people). He alone possesses the perfect Names and Attributes (that command the heart’s  love, hope, fear, gratitude and surrender to him Alone and none others). If he wasn’t these things, then he would not be deserving of worship. This rights of Allah is called [[id:1fc686ac-3a3f-4ba4-b006-b3f85944c586][Tawheed]] (categorised into 3), hence that the [[id:d73877f2-1d5d-4e34-a2a6-9bd3395c3974][only accepted religion is Islam]]. 

This is why we was created and [[id:1cbfb0c5-bf8b-405e-a9bd-0a2d45ac9ba5][what every messenger called to do]].

 #+begin_quote
  [[id:a4a5d6b5-7236-4368-b5fb-ddad20cd8e93][The Winnowing Winds (51:56)]]
  I did not create jinn and humans except to worship Me.
  
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/51/56
 #+end_quote

 #+begin_quote
  [[id:223c5e6b-f6c3-4325-ab8e-aa5e3bbee9cd][The Winnowing Winds (51:57)]] 
  I seek no provision from them, nor do I need them to feed Me.
  
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/51/57
 #+end_quote

 #+begin_quote
  [[id:25785d9e-7231-4ce7-b152-1a627ec84fba][The Winnowing Winds (51:58)]]
  Indeed, Allah ˹alone˺ is the Supreme Provider—Lord of all Power, Ever Mighty.
  
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/51/58
 #+end_quote



* Allah did not leave us neglected
:PROPERTIES:
:ID:       b1018d34-d2ce-4d0c-ab29-4445ea7f758e
:END:

 #+begin_quote
  [[id:b9227843-9fa7-4ced-854f-a1528336bf45][The Believers (23:115)]]
  Then did you think that We created you uselessly and that to Us you would not be returned?"
  — Saheeh International
  https://quran.com/23/115
 #+end_quote
 
 #+begin_quote
  [[id:d9d856fd-7270-4be1-a0fb-ac041f2d448c][The Prophets (21:16)]]
  And We did not create the heaven and earth and that between them in play.
  — Saheeh International
  https://quran.com/21/16
 #+end_quote

 #+begin_quote
  [[id:566b8f37-d71f-4c71-b0e4-79db07a020a1][The Smoke (44:38)]] 
  And We did not create the heavens and earth and that between them in play.
  — Saheeh International
  https://quran.com/44/38
 #+end_quote

 #+begin_quote
  [[id:44a06eac-df1d-43f8-8a38-fec182d1096a][The Resurrection (75:36)]] 
  Does man think that he will be left neglected?
  — Saheeh International
  https://quran.com/75/36
 #+end_quote

 #+begin_quote
  [[id:a4a5d6b5-7236-4368-b5fb-ddad20cd8e93][The Winnowing Winds (51:56)]]
  And I did not create the jinn and mankind except to worship Me.
  — Saheeh International
  https://quran.com/51/56
 #+end_quote
