:PROPERTIES:
:ID:       876cafe8-dbdb-4da5-9a43-cb6211080611
:ROAM_ALIASES: "bir walidayn"
:END:
#+title: Being Dutiful to Ones Parents
#+filetags: :book:

written by [[id:18b3ad1e-8b3e-4e19-b5cc-e6a581593ecc][Imaan Bukhari]]
 
I will colect similar hadith in a header and provide reference for them as we see based on the chapters of al-adab al mufrah
or i can do hadith 1, 2 ect 

1. [[id:e5817dba-1c51-4ca7-a2d1-a157d9abaa45][Abu Amr Ash Shaybani]] said: "The owner of this house informed us and he pointed with his hand to the house of Abdullah, referring to [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Ibn Masud]], "I asked the Prophet (ﷺ), which action is more beloved to Allah (ﷻ)? He replied, prayer performed on time, I asked, Then what? He said, then being dutiful to parents, I asked then what? He said Jihad in the path of Allah." He (Ibn Masud) said, "he related these things to me, and if I had asked him future, he would have told me more""
2. [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Ibn Masud]] said, I ask the Messenger of Allah (ﷺ): Similar to that of the previous narrations
3. Abdullah said, "I ask the Messenger of Allah (ﷺ), which action are the best? He said "Salah." Then he (Abdullah) said, Then what oh messenger of Allah? He said, "Then obeying the parents." He said Then What? He said "Jihad in the way of Allah." Then he remained quiet, and if I would have asked him more, he would have told me more.
4. [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Ibn Masud]] said: "The Messenger of Allah (ﷺ) said the best of actions - or action is prayer in its time, and being dutiful to the parents"
5. Abdullah said, "The Prophet (ﷺ) said, "The best actions is Prayer in its time, and Jihad in Allah's paths""
6. [[id:198c8513-15df-4e42-8f8a-dfe675a3a6f7][Ibn Masud]] said "I ask the Prophet (ﷺ) which actions is the best? He said "Salah, being dutiful to the parents, Jihad in Allah's path." And if I had asked him more, he would have said more".
7. (Same as above with a different chain)
8. [[id:6b12c2f3-ea24-49c2-8b3b-0eb83d5768d6][Sa'd ibn Abi Waqas]] said "Four ayats were revealed about me. The first was when my mother swore she would neither eat or drink until I left Muhammad (ﷺ). Allah (ﷻ) revealed, "But if they try to make you associate Something with Me about which you have no knowledge, do not obey them. Keep company with them correctly and courteously in this world (31:15)". The second was when I took a sword that I admire and said "Messenger of Allah, give me this!" Then the ayat was revealed:"They will ask you about your booty (8:1)". The third was when I was ill and the messenger of Allah (ﷺ), came to me and I said , "Messenger of Allah, I want to divide my property. Can I will away a half?" he said "No" "A third?" I asked. He was silent and so after that it was allowed to will away a third. The fourth was when I had been drinking wine with some of the Ansar. One of them hit my nose with the jawbone of a camel. I went to the Prophet (ﷺ) and Allah (ﷻ) revealed the Prohibition of wine. 
9. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] reported that a person said "Allah's Messenger (ﷺ) who amongst the people is most deserving of my good treatments? He said "Your mother, again your mother, again your mother, then your father, then your nearest relatives according to order (of nearness)"". He (Abu Hurairah) said, "They saw that for the mother it is two thirds, and for the father it is one third." Sufyan was asked, "Are two thirds for the mother in the narration?" he replied, "Yes, I heard it form Ibn Shubrunah, who narrated it from Umarah before I saw him; then I ask Umarah and he narrate it (directly to me)"
10. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] reported that a person came to Allah's Messenger (ﷺ) and said: "Who among the people is most deserving of a fine treatment for my hands?" He said "Your mother. He again said: then who (is the next one)? He said: Again it is your mother (who deserves the best treatment from you). He said: Then who (is the next one)? He said: Again, it is your mother. He again said: then who? Thereupon he said: Then it is your father""
11. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Huraira]] said, it was asked, "O Allah's Messenger (ﷺ), to whom should I be kind and dutiful?" He replied "Your mother." I asked "Who comes next?" He replied "Your mother." I asked, "Who comes next?" He replied, "Your mother." I asked, "Who comes next?" He replied, "Your father."
12. Abdullah bin Amr: narrated, A man said to the Prophet, "Shall I participate in Jihad?" The prophet (ﷺ) said, "Are your parents living?" The man said, "Yes." The Prophet (ﷺ) said "Do jihad for their benefit".
13. Abdullah ibn Amr said:"A man came to the Prophet (ﷺ), and made a pledge to him that he would do hijra. He left his parents who were in tears. The Prophet said, "Go back to them and make them laugh as you made them weep""
14. [[id:685a9a53-941d-46fe-b886-5935bbd43f2a][Anas bin Malik]] report that the Messenger of Allah (ﷺ), said "Anyone who wants to have his prevision expanded and his term of life prolonged should maintain ties of kinships."
15. Ibrahim At-Taymi said, "I do not compare my words to my deed without fearing that I will be called a liar."
16. [[id:685a9a53-941d-46fe-b886-5935bbd43f2a][Anas]] narrated that the Prophet (ﷺ) said, "Whoever want his life prolonged, and his provisions increased, then be dutiful to his parents."
17. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] report that the Prophet (ﷺ) said, "Three supplications are answered without a doubt: the supplication of someone who is oppressed, the supplicating of someone on a journey, and the supplication of the father for his child" 
18. Abu Umamah Al-Bahili narrates form the Messenger of Allah (ﷺ), who said, "There are three (people) from whom Allah will not accept any obligatory deed, nor supererogatory deed: This disobeyer (of his parents), one who is boastful (of favours on others) and the rejector of predestination." 
19. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] report Allah's Messenger (ﷺ) as saying, "A son does not repay what he owes his father unless he buys him and emancipates him if he finds him in slavery.
20. Abu Bakra narrates the Prophet (ﷺ) said thrice, "Should I inform you out the greatest of the great sins?" They said, "Yes, O Allah's messenger (ﷺ)!" He said, "To join others in worship with Allah and to be undutiful to one's parents." The Prophet (ﷺ) then sat up after he had been reclining (on a pillow) and said, "And I warn against give false witness", and he kept on saying that warning till we though he would not stop"
21. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] reported Allah Apostle (ﷺ) as saying: "Let him be hummled into dust; let him be humbled into dust". It was said: Allah's Messenger, "who is he?", He said "He who see either of his parents during their old age or he sees both of them, but he does not enter Paradise".
22. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] report Allah's Apostle (ﷺ) as saying: "let him be humbled into dust; let him be humbled into dust. three times, He who sees either of his parents during their old age or he sees both of them, and enter the Hell fire: or he does not enter Paradise.""
23. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates that the Messenger of Allah (ﷺ) said : "May the man before whom I am mentioned - and he does not sent Salat upon me - be humiliated. And may a man whose parents reach old age in his presence, and they were not a cause for his entrance to Paradise, be humiliated, be humiliated. and may a man upon whom Ramadan enters and then passes, before his is forgiven.""
24. Ka'ab Ibn Ujrah narrates that the prophet (ﷺ) said, "Bring the pulpit." Then when he (ﷺ) emerged and ascended the pulpit, he ascended the first step and said "Amin", Then he ascended the second (step) and said "Amin". Then he ascended the third step and said "Amin". Then when he had finished and descended the pulpit, we said "O messenger of Allah, we have indeed heard something from you today which we have not heard before. He asked, "And you heard it?" We replied "Yes". He said "Indeed Jibril appeared and said, "Distant (from the mercy of Allah) is he who reaches Ramadan and is not forgiven." So I said, "Amin". Then when I ascended the second (step), he said "Distant is he who doesn't not send salutation upon you when you are mentioned in his presence." So I said "Amin." Then when I ascended the third, he said "Distant is he who find his , or one of them, in old age and they are not a means of his entry into Paradise." so I said "Amin".
25. [[id:685a9a53-941d-46fe-b886-5935bbd43f2a][Anas]] said, "The Prophet (ﷺ) ascended the pulpit, when he went up one level he said, amin, then he went up another level and said, amin, then he went up a third level and said, amin, then he sat down. His companions asked, to what are you saying amin to O Messenger of Allah? He said, Jibril come to me and said, May the man before whom I am mentioned - and he does not send Salat upon me - be humiliated. And may a man who meets one of his parents or one of them and he did not enter Paradise. I said, Amin"
26. Ibn Abbas narrates, "The Prophet (ﷺ) said, "When a parents gazes upon their child and he make them happy, the child gain (the reward of) freeing a soul""
27. Ibn Umar narrates from the Messenger of Allah (ﷺ), who said, "Indeed, the strongest from the dutifulness is for a person to maintain ties with the loved ones of his father."
28. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates form the Prophet (ﷺ) who said, "Indeed, Allah has created the ties of kinship as [interwaving] branches". Allah says to the ties of kindship: "Are you not pleased that I enter into Paradise the one who maintains you, and I enter into the Fire the one who severs you?"
29. Jubayr ibn Mutim narrates that he heard the Prophet (ﷺ) say , "A person who severs ties will not enter Paradise." 
30. Jubayr ibn Mutim narrates the same (as the above with a different chain)
31. [[id:685a9a53-941d-46fe-b886-5935bbd43f2a][Anas]] narrates that Allah's Messenger (ﷺ) said, "Whoever desires for his sustenance to be expanded and his life to be lengthened should maintain his ties of kinship."
32. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates that the Messenger of Allah (ﷺ) said, "Indeed, rahim (ties of kindship) is a branch [derived from Rahman the All-merciful]". It says "O My Lord! I have been wronged! O My Lord! I have been severed! O My Lord! O My Lord! O My Lord!" H answered it,"Are you not pleased that I sever the one who severs you and I maintain the one who maintains you?"
33. Abu Ad-Darda narrates from the Prophet (ﷺ), who said "The disobeyer [of parents] will not enter Paradise, nor the alcoholic, nor someone who denies divine decree."
34. Abdullah ibn Amr narrates, "The Messenger of Allah (ﷺ) said, "The person maintains ties of kinship is not someone who [merely] reciprocates; rather the person who maintains ties of kinship is he who maintains them when they are severed"
35. [[id:b79b21c1-8212-4340-a9cf-b95f3264ad89][A'ishah]], the wife of the Prophet (ﷺ), narrates form the Prophet (ﷺ), who said "Rahim (ties of kindship) is a branch [as it is derived form Rahman]. Allah (ﷻ) said: Therefore, whoever maintains it, I will keep good relations with him, and whoever severs it will server him" 
36. Abdullah ibn Abi Awfa narrates from the Prophet (ﷺ), who said, Indeed, mercy does not descend upon a people who have among them a person who severs ties of kindship.
37. Jubayr ibn Mutim narrates that he heard the Prophet (ﷺ) say, "The person who severs the ties of kinship will not enter Paradise." 
38. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates that the Prophet (ﷺ) said, "Indeed, rahim (ties of kinship) is a branch [as it is derived from Rahman (All-merciful)]. It says, "O My Lord! Verily, I have been served! O My Lord! I have been wronged! O My Lord! O My Lord! O My Lord!" So, He answers them, "Are you not pleased that I sever the one who severs you and I maintain the one who maintains you?"
39. Ibrahim at-Taymi said, "I imagined myself in Paradise, eating from its delicacies, drinking form it's beverages, cohabiting with its inhabitants and attaining what I desired. Then I said "O Soul, make a wish." It replied, "I wish to return to the world in order to increase in good deeds so that I increase in reward."Then I imagined myself in hellfire, eating form it cured tree and drinking from its boiling water [and cohabiting with its inhabitants]. Then I said "O soul, make a wish." Ir replied, "I wish to return to the world to repent so that I may be saved from the predicament I am in" Then I said to it, "O soul, you are [currently] in your dreams, so do good deeds [as you are still in the world]."
40. Jabir ibn Abdullah narrates, "The prophet said (ﷺ) "When one of you come [from the Friday Prayer] and the imam is delivering the sermon, then he should perform two unit of prayers (rak'ahs)." Bukhari says, "And this is the practice we adopt"
41. Sufyan Ibn Uyaynah said, "Whoever does not know whilst he is aware the he does not know, then his is larened"
42. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Huraira]] narrates, A man came to the Prophet (ﷺ) and said "O messenger of Allah, advise me and make it concise so that I may remember it." He replied, "Do not become angry." The man asked him [the same] once or twice and hre replied each time, "Do not become agnry"""
43. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates, "The Messenger of Allah (ﷺ) said, "The strong one is not he who overpowers peoples, rather the strong one is he who controls himself."
44. Ibrahim ibn Umar ibn Kaysan said, "Ibn abi Najih spent thirty years without uttering any world which would harm his companions.""
45. Ibn Uyaynah said, "Do you know what salam is? Salam, is that you are safe from me, you are secure form me."
46. Abu 'Abdullah al-Musnadi narrates, "Salm ibn Salim came to Ibn Uyaynah and began informing him, "I have done this and that". Ibn Uyaynah looked at him and said, "Your intellect has satisfied my view regarding you." Allah says, "And turn away form the ignorant"
47. [[id:b79b21c1-8212-4340-a9cf-b95f3264ad89][Aishah]] narrates that the Prophet (ﷺ) said to her "Go ahead and take retribution." 
48. Miqadam ibn Madi Karib - who met the Prophet (ﷺ) - narrates, "The Prophet (ﷺ) said, "when one of you loves his brother, he should inform him that he loves him""" 
49. I heard Musa ibn Isma'il say, "I heard Abu Asim say, I have never backbitten anyone since I learnt that backbiting harms it perpetrators"
50. Muawiyah ibn Qurrah, narrates form his father, who said "A man said, "O messenger of Allah (ﷺ), whenever I slaughter a goal, i feel compassionate towards it," or [he said], "I have compassion on the goat [preventing me form slaughtering it]". he said twice, "Any if you are compassionate to [even] the goal, allah will be compassionate to you."
51. Nawwas ibn Saman narrates that he asked the Messenger of Allah (ﷺ) about piety and sin. He said, "Piety is good character, and sin is that which rankles in your heart so that you dislike other people becoming aware of it".
52. Ibn 'Umar narrates, "I heard Allah's Messenger (ﷺ) saying whilst he was on the pulpit, "Beware, indeed turmoil (fitnah) will appear form here, pointing towards the east, "from where the horn of the devil will appear"
53. Ibn 'Umar narrates, "I heard the Allah's Messenger (ﷺ) stand and give a sermon saying, "Beward, indeed turmoil (fitnah) will appear from here, from where the horn of the devil will appear."
54. Abdullah ibn az-Zubayr narrates, "Zubayr said, "When [the following verse] was revealed: "Then indeed, on the Day of Resurrection, you will be disputing before your Lord, Zubayr said, "O messenger of Allah (ﷺ), our disputes will be repeated to us after what happened between us in the world?" He said, "Yes", so I said, "Indeed, the matter is most serious."
55. Abdullah Ibn az-Zubayr narrates, "When [the following verse] was revealed: "Then indeed on the Day of Resurrection, you will be disputing before your Lord." (Qur'an 39:31). Zubayr said, "O messenger of Allah (ﷺ), what happened between us inthis world will be repeat to us, including even the most intrinsic of sins?" He said, "Yes, they will be repeated to you until every rightful person is given his due" Zubayr said, "By Allah, indeed the matter is serious".
56. Ibn Umar said, "When [the following verse] was revealed: "Then indeed, on the Day of Resurrection, you will be disputing before your Lord (Qur'an 39:31)". We did not know it interpretation. Then when the turmoil (fitnah) occurred, we said, "This is what our Lord promised us we would be disputing about."
57. Usamah ibn Zayd narrates that the Prophet (ﷺ) said, "Do you see what I see? I see turmoil's occurring between your homes." 
58. Usamah [ibn Zayd] narrates, "The Prophet (ﷺ) said, "Do you see what I see? I see turmoil's occurring between your house like droplets of rain."
59. Kurz ibn Alqamah narrates, "A Bedouin asked the Prophet (ﷺ), "Is there a limit for the spreading of Islam?" He said "Yes. Whichever household Allah intends good for, Arab, or non-Arab, He causes Islam to enter. Then turmoil's will occur as though they are darknesses. "The Bedouin then remarked, "Not at all [i.e this will not occur]." He said, "Certainly [it will occur]. By the One whose Hand is my soul, you will then return therein as black snakes, some of you striking the necks of others."
60. Abdullah [Ibn Umar] narrates that he heard Allah's Messenger (ﷺ) whilst he was facing the east, saying, "Beward, turmoil will appear from here; beware turmoil will appear from here, from where the horn of the devil will apear" 
61. (Same as above)
62. (Same as above)
63. Abu Bakrah narrates "The Prophet (ﷺ) said,"There is no sin which Allah is swifter to punish in this world, in addition to the punishment, which is accumulated for him in the Hereafter, than the sin of serving ties of kinship and injustice"
64. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates the Prophet (ﷺ) said "Indeed, I have relatives with whom I maintain ties of kinship, whilest they sever them; I am forbearing to them and they behave ignorantly towards me; and I am good to them, whilst they are bad to me." He said "If things are as you say, it is as though you are feeding them hot embers, and there will always be support from Allah with you as long as you continue to do that."
65. Abdullah bin 'Amr narrates form the Prophet (ﷺ), who said, "The person who maintain tie of kinship is not someone who merely reciprocates. Rather the person who maintains ties of kinship is someone who maintains ties when his kin turns away from him." 
66. Bara' narrates, A Bedouin came and said , O prophet of Allah (ﷺ)! Teach me an action that will enter me into Paradise. He said, "You have asked a broad question, even though you remark was succinct. Free a soul and set a slave free."  He said "Are they not the same" He said, "No. Freeing a soul is that you free a soul [yourself] and setting a slave free is to support or contribute to his freedome. Also gifting an animal full of milk , and maintaining good ties with an oppressive relative. If you are unable to do that, then enjoin good and forbid evil. If you are unable to do that, then restrain your tongue form everything except that which is good."
67. Hakim ibn Hizam narrates that he said to the Messenger of Allah (ﷺ) "Do you think there is any reward for the deeds I performed in the Time of Ignorance (Jahiliyyah), such as maintaining ties, freeing a slave or charity? Hakim narrates, The Messenger of Allah said (ﷺ), "You become a Muslim will all the previous good deeds." 
68. Maymunah, the wife of the Prophet (ﷺ), narrates that she had a slave girl and set her free. When the messenger of Allah came to her, she informed him. He said, "May Allah reward you for it; if you had gifted her to your maternal uncles, you reward would have been greater" 
69. (Same as above)
70. [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] narrates from the Prophet (ﷺ) who said, "Indeed, Allah created the creation and at the point when he had completed it, the ties of kindship said, "This is the place for anyone seeking refuge in you from being severed". He Allah (ﷻ) said, "are you not content that I enjoin the one who enjoys you and I sever the one who severs you?" It replied, "Yes indeed, my Lord" He said, "Then you have that." Allah's messenger then said "recite if you wish: "So would you perhaps, if you turn away, cause corruption on Earth and sever your ties of kinship? Those are the ones who Allah has cursed, so He made them deaf and blinded their eyes." (Qur'an 47:22-23) 
71. [[id:b79b21c1-8212-4340-a9cf-b95f3264ad89][A'ishah]] narrates, "The messenger of Allah (ﷻ) returned to Khadijah trembling. He entered and said, "Cover me! Cover me! "Then when his fear dissipated, he said to Khadija, "I fear for my life." Khadijah as replied, "Glad tiding. I swear by Allah, Allah will never disgrace you. Indeed, you speak the truth, you maintain the ties of kinship and bear the burden [of other], You honour guest and assist those with a deserving need." The Khadijah took him to Waraqah ibn Nawfal ibn Asad, who has become a Christian, a blind old man who would read the Gospel in Arabic. Khadijah said to him, "O my uncle, listen to your nephew!" Waraqah ask him, "O my nephew! What do you see?" Allah's Messenger (ﷺ) described what he saw. Then Waraqah said, "This is the archangel whom Allah sent to Moses. I wish I were young. I wish I would be alive when your people drive you out". He asked, "Will they drive me out?" He replied, "Yes. No one has come with what you have come with without being treated with hostility, and if I remain alive until your day [when this will occur], I will support you strongly." 
72. Bilal ibn Sa'd narrates from his father that he said, "O messenger of Allah (ﷺ), what is [our duty] to the caliph after you?" He said, "The same as your duty to me, so long as he is just in judgement, fair in distribution and merciful to kin. Whoever does anything beside that, then he is not from me, nor am I from him"
73. Jabir narrates  a person from the Banu Udhrah set a mudabbar slave free [A mudabbar slave is one whose freedom is conditioned upon the masters death]. This news reached the Messenger of Allah and he said, "Have you any wealth beside him?" He said, "No." The messenger of Allah said "Who will purchase him from me?" So Nu'aym ibn 'Abdullah an-Naham bought him for the eight hundred dirhams, which he gave to the Messenger of Allah. He gave it to [the man who had freed the slave] and then said "Start with yourself and spend it on yourself. If anythings is left, the spend on your immediate family. If anything is left after spending on your immediate family, it is for your relatives [i.e distant family]. If anything is left after spending on your relatives, then spend it in such and such manner," saying, "in front of you, on your right and on your left".
74. Sa'id ibn Sam'an reports, "I heart [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]] seeking refuge form the leadership of juveniles and fools?" Sa'id ibn Sam'an continues, 'Ibn Hasanah alJuhani informed me that he asked [[id:bbaf35e6-7daf-45f7-a188-2b83ad034111][Abu Hurairah]], "What is the sign of this?" He replied, "That the ties of kinship are severed, the misguided leader is obeyed and the guided leader is disobeyed"
75. Amr ibn 'Aas narrates, "I heart the messenger of Allah (ﷺ) calling out quietly, not loudly, "My friend is only Allah and those who believe; however, they [i.e. non-believers] have a tie of kinship [with me] which i will keep moist with its wetness (i.e. maintained adequatly)"
76. Usamah ibn Zayd narrates from the Prophet (ﷺ) who said, "I have not left after ma a temptation more calmitous to men than women."
    
    
