:PROPERTIES:
:ID:       032f99c5-98f9-4b1e-882b-d1d5bedcc1ff
:END:
#+title: 'Abd al Rahman bin Nasir al Si'di
#+filetags: :Imaam:

Al-Sa'di was born in the city of Unayzah, al-Qassim, Saudi Arabia on 7 September 1889. His father, Nasir al-Sa'di, was an imam and preacher in a mosque in the Unayzah. His mother, Fatimah bint Abdullah al-'Uthaymeen, died when he was four years old, and his father died when he was seven. He was initially cared for by his father's second wife and was later transferred to the guardianship of his oldest brother, Hamad ibn Nasir al-Sa'di. He completed his memorisation of the Qur'an by the age of eleven and then pursued religious education from the scholars in his locality. In his teenage years, his fellow students began to refer to him for help in their studies.

Follower of the mathhab of Iman Ahmed

Wrote over 40 book and is known for the tafsir of the Qur'an. Hence he tries to derived the ruling from the text and make it easy to understand for the student. 
