:PROPERTIES:
:ID:       413a9dfe-a18a-4c05-9cd6-1308b3adb99b
:END:
#+title: al sabab - the casue/reason

* al-Sabab – The Cause/Reason
Definition
Examples

- cause - al-sabab
  perform salah, on it's specific time
  eg. make sure there water in the table before the class
  - if the reason is not there, then the ruling of it is not there

    
** •Linguistic Definition:
A sabab literally means a "cause," "means," or "reason" that leads to something else. For example, a rope used to draw water from a well can be called a sabab, as it is the means by which the water is brought up.

** •Technical Definition:
An act upon which a legal obligation, prohibition, or ruling depends;

*its presence mandates the implementation of the ruling, while its absence results in the suspension of that ruling.*



** •Explanation:
A sabab therefore, refers to a cause or reason that, when it occurs, results in a legal ruling being applicable.

It is a condition or factor that triggers the application of a specific legal rule or obligation.

It is an external, objective event or situation that the Shari'ah has designated as the cause for a legal ruling.


** examples
Allah has made the reaons


•Zakah: Possession of wealth that meets the minimum threshold (nisab).
- wealth is the reason here
  
•Salah: The arrival of specific prayer times (e.g., the time for Dhuhr or Maghrib).
- the time entering is the reason
  
•Fasting in Ramadan: The sighting of the crescent moon marking the beginning of Ramadan.
- the moon sighting is the reason
  
•Inheritance: Closeness in relation, marriage or freed slave.
- relations, marraige and freed slave is the rason

•Punishment for Theft: The act of stealing a certain amount of property in a certain way.




** types of sabab

Types of Sabab
*** Sabab
**** A Sabab that is not within ones control
- we didn't determine which family we will go into
  - this is decreed
**** A sabab which is within ones control
***** legislatively command
- e.g have some wealth, because will help you will the other obligation. e.g purchase water
 - default of nikkah recommended, but the nikkah contract is the reason of obligation to fulfil the man desires, and for the man to clothes here 
***** prohibited
- theft, (the sabab is) choosing to stealing
  - hence hand copped
- zani, (the reason is) he choose to commit the zina
    - hence lashed and banished 
***** permitted within ones choice
- i.e choosing to eat meant
  now he has to choose halal meat


