:PROPERTIES:
:ID:       3736fd73-be2b-428c-9fa4-443e18f20e3e
:END:
#+title: He who see either of his parents during their old age or he sees both of them, but he does not enter Paradise

Allah mentions how Ibrahim speaks to his disbelieving father. He calls him “ya abati”, he keeps the best adab and make dua for his father, even when his father is harsh.
 #+begin_quote
  [[id:6440b3b3-ed3a-4f55-82a5-a4d510f0fe66][Mary (19:43)]] 
  O  dear father! I have certainly received some knowledge which you have not received, so follow me and I will guide you to the Straight Path.
 #+end_quote
 #+begin_quote
  [[id:2d4d8c9a-7b72-4598-87d6-16d19bea7086][Mary (19:44)]]
  O  dear father! Do not worship Satan. Surely Satan is ever rebellious against the Most Compassionate.
 #+end_quote
 #+begin_quote
  [[id:1ec0212b-ab66-4280-9647-e5d8982c5f64][Mary (19:45)]]
  O  dear father! I truly fear that you will be touched by a torment from the Most Compassionate, and become Satan’s companion ˹in Hell˺.”
 #+end_quote
 #+begin_quote
  [[id:92006116-468f-4715-bf8f-5b7d06ef5ffd][Mary (19:46)]] 
  He threatened, “How dare you reject my idols, O  Abraham! If you do not desist, I will certainly stone you ˹to death˺. So be gone from me for a long time!”
 #+end_quote
 #+begin_quote
  [[id:971f90a3-65f0-454a-9a25-9c55a1497f1d][Mary (19:47)]]
  Abraham responded, “Peace be upon you! I will pray to my Lord for your forgiveness. He has truly been Most Gracious to me.
 #+end_quote

Then Ibrahim with his son Ismamil: the same words comes back
 #+begin_quote
  [[id:3ef22e15-e7a2-492f-afee-3af199f1db5e][Those who set the Ranks (37:102)]] 
  Then when the boy reached the age to work with him, Abraham said, “O my dear son! I have seen in a dream that I ˹must˺ sacrifice you. So tell me what you think.” He replied, “O my dear father! Do as you are commanded. Allah willing, you will find me steadfast.”
  — Dr. Mustafa Khattab, The Clear Quran
 #+end_quote

The scholars say if you are going to be good to your parents then you're children will be good to you. We saw it with Ibrahim and his father, then with Ibrahim and his child.
