:PROPERTIES:
:ID:       8bf3dd37-eb8f-4410-a4b3-c54a8265aae3
:END:
#+title: Allah lead astray

This doesn't not mean that Allah has oppressed the person, but rather he has given mankind free will. We have the choice to choose which path to take. In their heart is a disease and they choose to go astray.
 #+begin_quote
  [[id:d36523c8-e066-45c9-bf80-df7f82032464][The Cow (2:10)]]
  In their hearts is disease, so Allāh has increased their disease; and for them is a painful punishment because they [habitually] used to lie.
  — Saheeh International
  Footnote - 1
  The "disease" mentioned here includes doubt, hypocrisy, arrogance and disbelief.
 #+end_quote

In their heart is a disease, so they choose to go away from the path and didn't want to cure the disease of their heart, he (ﷻ) increase them in their disease, when they turned away, they turned their hearts away. Allah (ﷻ) showed the evidences and they turned away from it.

We have the natural inclination called fitrah, and a natural inclination to do goodness and even if we didn't have the Qur'an, we will know that there is a creator to be worshipped from his signs. After the proof has been established over them, they still turn away form the path, while increasing in their disbelief and transgression, so they turn away, Allah (ﷻ) turn their heart away, Allah seal their heart and their hearing and a cover on their sight
 #+begin_quote
  [[id:268ad1bd-3c92-4021-8ca4-b3fb581f3b1d][The Cow (2:7)]]
  Allah has sealed their hearts and their hearing, and their sight is covered. They will suffer a tremendous punishment.
  — Dr. Mustafa Khattab, The Clear Quran
 
  https://quran.com/2/7
 #+end_quote
 
they are deaf dumb and blind and they will not understand, Allah kept giving them chances until the door has been close.
 #+begin_quote
  [[id:fb825e4a-a60a-4f08-8174-aa69b3759182][The Cow (2:16)]] 
  They are the ones who trade guidance for misguidance. But this trade is profitless, and they are not ˹rightly˺ guided.
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/2/16
 #+end_quote
 #+begin_quote
  [[id:c8986906-22bb-4cd7-9995-e491b69dd33f][The Cow (2:17)]]
  Their example is that of someone who kindles a fire, but when it lights up all around them, Allah takes away their light, leaving them in complete darkness—unable to see.
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/2/17
 #+end_quote
 #+begin_quote
  [[id:10251e96-dd40-45ca-8170-04de1da28f9a][The Cow (2:18)]]
  They are ˹wilfully˺ deaf, dumb, and blind, so they will never return ˹to the Right Path˺.
  — Dr. Mustafa Khattab, The Clear Quran
  https://quran.com/2/18
 #+end_quote

For example at the time of Musa, pharaoh had evidence established over him one after another. Then after, Musa made dua where he asked there heart to be seal, and only for open it for them until they've seen the punishment.
 #+begin_quote
  [[id:38f62ebe-fadf-4f41-8d72-8fd1bbe9f4bb][Jonah (10:88)]]
  And Moses said, "Our Lord, indeed You have given Pharaoh and his establishment splendor and wealth in the worldly life, our Lord, that they may lead [men] astray from Your way. Our Lord, obliterate their wealth and harden their hearts so that they will not believe until they see the painful punishment."
  — Saheeh International
  https://quran.com/10/88
 #+end_quote

[[id:308f745f-1fa6-4464-b510-24e7ec1cb3db][Allah does not oppress anyone]]. In hadith qudsi Allah (ﷻ) says: 
 #+begin_quote
 I have forbidden oppression for Myself and have made it forbidden amongst you, so do not oppress one another.
 #+end_quote
Allah (ﷻ) is  the most just, the most gentil, the most generous, extremely generous the one who give in abundance.

Allah lead astray is understood by this, that he chose to leave the Shari'a and Allah let him go completly. 

