:PROPERTIES:
:ID:       266135f3-4e35-4c08-8460-3fa55e673aa8
:END:
#+title: lesson 9 and 10

#+title: Usul al-Fiqh – Lessons 9 & 10
#+subtitle: Usul min ‘ilm al-Usul
#+date: 2024-12-07
#+filetags: :usul_al_fiqh:lesson9:lesson10:mukallaf:taklif:general:specific:

* Lesson information
** Module and course book
- Module: *Usul al-Fiqh 1*
- Course book: *Usul min ‘ilm al-Usul*
- Lessons: 9 & 10 (Saturday 7 December 2024)

** Contents of this presentation
1. Revision of Commands & Prohibitions
2. Revision of Prohibitions
3. Who is the Mukallaf?
4. The Conditions of Takleef
5. The Signs of Maturity
6. Conditions of Validity & Obligation
7. The General & the Specific
8. The General: Definitions & Expressions
9. The Categories & Types of General

* The Mukallaf
** Definition
هو: المخاطَب بما اقتضاه خطاب الشرع من الأحكام الشرعية، من الفعل والترك أو التخيير.  
والمكلَّف بمعنى: الذي توجَّه إليه خطاب الشرع ليفهمه وفق شروط التكليف.

- *Translation*:  
  “It refers to the one addressed by the command of the Sharī‘ah regarding the legal rulings — whether to act, abstain, or choose.  
  The *mukallaf* (legally accountable person) is the one to whom the command of the Sharī‘ah is directed for understanding, based on the conditions of accountability.”
  

** The structure of legal rulings
- The Laws of the Sharī‘ah (الأحكام الشرعية)
- The Lawgiver – Allah (الحاكم)
  - The hakim
- The Law / Ruling (الحكم)
  - the takify and wadiyah 
- The Judged Matter / Subject of the ruling (المحكوم فيه)
  - sabab the reason, theft is haram 
- The One Addressed – the *mukallaf* (المحكوم عليه = المكلَّف)

* The Conditions of Takleef (شروط التكليف)
    - someone who is close to mature
      - very close to understand right and wrong
        - these children should be encoreanged
          - from the age of 7 and be deciplied till the age of 10
            - only  iman ahmad say for all action and the rest say only for salah
              - hadith about direct you're child from 7 and hit them from age of 10 to decipine
                - you hit them  (i.e you don't harm) someone except that you left something obligatory
                  - reason, becasue it take time to get the habit of salah
                    - from 7 and more so from 10
                      - are the action accepted from here and who get the reward
                        - there a hadith
                          - saying yes the child has hajj
                            - it mean the child has the reward of hajj but still needs to preform it
                              - he still need to do it after
                                - the women get the reward as well
                                  - let them get used to it so it don't feel miles aware
                                    
    - البلوغ :: *Maturity*  

** The Signs of Maturity
he meets any one of the sing below

- بلوغ سن خمس عشرة سنة قمرية :: Reaching the age of 15 lunar years
  
  eg 14 or 14/half, hadith of ibn umar participating in battle, in the battle of khadak he was 15 and not in the battle in badr
  
- الاحتلام :: Release of seminal fluid (wet dream / ejaculation)
except due to a medication reason
- the pen has been lifted for a young child untill the seminal fluid
  
- الإنبات :: Growth of pubic hair
- thick hair that is rquired to be shaved
  - that which is require to be shaved
    - prinson of bani qraibah, the book the treaties and show many sign of betrains, they we're then order to be killed, the shahabah look for the ones that had private part
      - why is this an evidence, since you can't kill a child
        
- الحيض :: Menstruation (for females)
  - Allah don't accept the salah of mentrauting women exept she wear a khimar
    - girls don't need to cover hari
- الحمل :: Pregnancy (for females)
  e.g some scholars says it obvious
  - it could positible that a women might not have mensense
    - but with the relation of the husband, she becomes mature

- العقل وفهم الخطاب :: *Sanity and the ability to understand speech*  
- sanity is you understand speech 
  - the one who is insane is not accountable, even if he's mature
    - the pen has been lifted for him
      - the insane person until he has sanity
        
- القدرة على الامتثال :: *The ability to comply (physical/financial capacity)*  
  - carry out the action that has been acted for you
    - e.g. can't fast during traveling
    - needs to be according to the text
      - no soul should be burden to hardhsip
- الاختيار :: *Freedom to choose; not being forced*  
  - if you are force, you won't be held to accountable since you was force
    - exception of this is ibadat
      - e.g hadith of the hajj with the mother and son
        
- العلم بالتكليف :: *Knowledge of the ruling / awareness of accountability*
  - knowing that Allah will hold you accountable
    - knowing what is haram and halal
    - Allah don't punish the people unless he has sent a messenger
      - hence this is a condition of taklif
        - masil
          1. when is this ignroace accept in sharia
             - the law that are apprent, not abiluigty, e.g 5 prayer and fasting and staying away from zina and can't be denied
               - if he lives in a islam land
                 - or kafir but has access to this knowledge
                   - this person is not excued
                     - because this is a necessity for him
                       - hence this knowledge is the obligatory which we should be seeking
          2. thing that one will not nessary know and will be excused for this
             - e.g details of buying and sell, the details of riba 
               - here imaan shafee says not accoutable except the have the ability to learn but not due to lazyness or try to trick allah by saing i don't know so it's okay and everyint is halal
                 - this perons will be held accoutnable
                   - but if ther person think is halal becasue he asked someone and trust him
                     - this is ok

          3. someone became just must or far away form any type of knowledge
             - he is not accountable liek categorty 1 and 2
               - e.g living in the amazon forest
                 - they will have their own test in yamal qiyam
                   - hadith the people who was insane and did not get islam reason or udnerstand it
                     - allah will comand them to go to the fire
                       the one that went - the fire became cool for him
                       the one the argued - the fire is for him, since they argued with allah then they would have argued with the prophet and messenger
          4. is a person going to be held account if, he knew about he cammand and probition,  but not the conquence i.e the punishment or reqard
             1. is the ignroarce a reason to be punished or not
                - nowing somehting is haram but didn't know the punishment
                  - is his ignoreance of the punishment or for the act
                    - did not know the conequcen of carrying out the prohibution 
             2. he will be punished
                - e.g maiz, he said my people will kill me and went the to prohet pbuh but he was killed when he went to the prophet pbuh, this shows that you'll still be punished if you didn't know the conciqunce due to the punished of adultry
                - so it punishment doen't drop even if they didn't know
                  
- There is still an obligation for the one who is insane and a child
  - it will be based on sitation
    - there gardian will be accountable 
      - zakat - for the one who is in charge of it
        - there are connect ot reason, regarless who onwn it
          - a child damange a car
            - there a reason for the damage
              - he will not be sinful, but the garudain must resove it
                and the child is the reason due to it
      
why is islam not a contion in takilify
- the kafir will be punished for salah and all of the action that allah prohibited

  - even if they prayer, there good deed/action won't be accepted
    - becasue  islam is a condition for the acceptance of the action, but not a condition for accountablity/ talifiyka 
    
* Conditions of Validity vs Conditions of Obligation
** شروط الصحة – Conditions of Validity
- These are the conditions for the *validity* of an act of worship, transaction, or other legal act.
- The *mukallaf* must fulfil them for the act to be sound in the sight of Sharī‘ah.
- If these conditions are not met, the act is *invalid* and will not be accepted.
  - islam is a condition for valditiy
    - so theire carity won't be accepted
      simialar, reacting the age of maturity, the action is accept but not obligaotry
      - why usool scholars mention this 
        - e.g kafir should be fasting during ramanadam, so we will faslitating in haram
          - there are 24 different opions
            iman ahmed
            - both are held accoutable
        - deal with muslim on the deafult position so you don't need to ask. 

** شروط الوجوب – Conditions of Obligation
- These are the conditions for an act to *become obligatory* upon the *mukallaf*.
- When these conditions are fulfilled, the person is required to perform the act.
- If they are not fulfilled, the act may not yet be obligatory (e.g 7-10yr) (even if performing it would still be valid).

* Principle about legislative wording
- “The default position of words used in a *legislative* context is to carry their *legislative meanings* unless proven otherwise.”

* Preventions / Obstacles to Legal Accountability (موانع التكليف)
Mawani’ al-Taklif are the obstacles to legal accountability in Usul al-Fiqh.
- These are factors that prevent a person from being held blameworthy, even if they meet a sign of maturity and accountability when these obstilbes are present.


** Main obstacles
- الجهل :: *Ignorance* – not knowing the ruling or not having learnt it.
- النسيان :: *Forgetfulness* – genuinely forgetting the ruling at the time of action.
- الإكراه :: *Coercion* – being forced to do something under compulsion.

When these are present, a person may not be held responsible for leaving an obligation or committing a prohibition.

* KILL Summary of the Mukallaf – The one held accountable
- The *mukallaf* is the one who is held accountable for all *commands* and *prohibitions* of the Sharī‘ah.
- A person becomes a *mukallaf* when *any one* of the following signs of maturity appears:
  1. Reaching 15 lunar years.
  2. Growth of hair around the front private organ.
  3. Releasing seminal fluid.
  4. Menstruation.
  5. Pregnancy.
- The main preventions of accountability are:
  1. Ignorance.
     - e.g saying something in sleep
       - but if he breaks something in sleep then it counts
  2. Forgetfulness.
     - he will not be punished for his action
       - Allah will have mercy for him
         - eg fasting and breaks his food
           - his fast is not broken
  3. Coercion.
     - being forced
       - you can't bear, it i.e to the point of commit suicide 
       - you can bear it, you can still be accountable, just going to prison
         
- The burden of obeying commands and abstaining from prohibitions is directed at *both Muslims and non-Muslims*.
  
----
the insane
 - for the person who is insane he is not accoutnable for him in the duyah and the akhira
   - as for ibadah action
     - allah did not request it or required it
     - there is not conquece for it in the dunya and akhira
       - however if he harmed a peron or damaged a proverty or steal
         - he's not accountable in the dunya
           - but he and his gardian are requided to fix the problem
       - even  if he a sane person breaks something in sleep then it counts, because he is still accountable in the dunya
               
  
* The General and the Specific
** Overview of manners of deriving from evidences
- Commandments & Prohibitions (الأمر والنهي)
- The General & the Specific (العام والخاص)
- The Absolute & the Restricted (المطلق والمقيد)
- The Obscure & the Clarifying (المجمل والمبيَّن)
- The Apparent & the Interpreted (الظاهر والمؤوَّل)

* General Texts / Terms (العام)
** Definition
- “An all-encompassing word that includes all its individual elements without restriction.”
- Or: “A word (or name) that encompasses everything it applies to, in a single usage, without limitation.”
  
  - e.g when you entering a masjid, you can sit down and till you perform 2 rakat, this is said in a general term.
    e.g. there is no nikah wihtout witness, so it doesn't matter if she is a virgin or not or divorced or not, it dones't matter becasue it's general
    - so it not for particlar parties
  - all the water from the sky is pure
    - e.g rain, snow

- the law is general and allowed in different curcumstances
  - to claim it is haram you need to prove it


** What do general terms necessitate?
- It is *obligatory* to act according to the general wording.
- There is *no requirement* to search for an evidence that specifies it *before* acting upon it.

  - these are general statement in text
    - even in the case on an-nazar
      - he say a general statement so it still  counts even thought he said it as a genral statement  

  
* Expressions that signify generality (Forms of General (Al-'Am))  
** 1. Explicitly general words
ما كان بمادته نصًّا في العموم، وهي: *كل، جميع، كافة، قاطبة*  
Words whose very form is explicit in generality, such as:
- “كل” – all / every
- “جميع” – all / entire
- “كافة” – altogether
- “قاطبة” – all without exception
- These word are all general terms
  - e.g every sould shall taste death
    -  because of kuloo
  - e.g all the angels postrated to adam
        
** 2.Nouns of condition ( أسماء الشرط – )
- Such as: من، ما، أين، متى … when used in conditional structures.
  - this format singfies genrality
  - e.g who ever comes to this room, you will honor him
    - eg. if a man or woman doesn't matter its in general, you will honour them in all types of its way, in the gerenal sense
    - if zaid come make sure you honur him
      - you made honur here is general
        - if you when he comes
          - this means when ever he comes

** 3.Interrogative pronouns (أسماء الاستفهام)
- Such as: من، ما، أيّ … when used to ask about something in a general way.
  - the pronouns used to ask question, not asking to ask for an awnser but to specifcy generality
    - Where ever you go death will over come you
    -  "Who is that will bring forth gushing water" 67:30
** 4.Relative pronouns (الأسماء الموصولة)
- Such as: الذي، التي، الذين، من … which/that/who – when referring to a class in general.
  - those people or them
    - make sure you are honerable to them
      - this singinfies generaltiy
- e.g. all of those who eat the wealth of the orhpans
  - those who say uff to their parents
  - this uff will be punisable to everyone who say it to their parentsk
  - "and those who strive for Us - we will surely guide them to Our way" 26:69
** 5.Indefinite nouns in certain contexts
النكرة في سياق النفي، أو الشرط، أو النهي تفيد العموم  
- An *indefinite noun* (نكرة) in the context of:
  - negation,
  - condition,
  - or prohibition  
  signifies generality.
eg.
  - e.g they house, the hosue it self is not know and is general
  - you don't know who it belogngs to  
   - "there is no true god but Allah"3:63
     - this god, here is general, all types of things that are worshipped
  - every type of intermacy is prohibeted in hajj
    - every type of evil
      - every type of arguing 
** 6.Definite noun by annexation (iḍāfah) (المعرف بالإضافة)
- A noun made definite via possession/annexation (*X of Y*), whether singular or plural, can indicate generality in the possessed group.
  - something that (denfinate) is know
    - is owned by something (posseive conjuectio) in sentence
    - you will not able to count all of the blessing of Allah, even if you sit an count
     -  blessing of Allah, this is connected, hence the blessing here is refered to all of the blessig
       - blessing is a noun
- the wife of the prohet, you're not like any of the type of women
  - in the same form, all of you child are deserving of youre inherance
    - you own you children 
    
** 7. Definite noun with the inclusive “al-” (المعرف بالألف واللام الاستغراقية)
- A generic noun defined with *al-* (ال) of total inclusion (الاستغراق) indicates generality, e.g. *الناس، المؤمنون*.
- he created all of mankind weak
  - al insan here is all of mankind, everyonek
- the children (all the chidren) reach the materity, let them ask for permission before entering you're room
  - the men (all of men) are maintainer for their women
    - 

    
* Categories and types of generality (أقسام العام)

** العام الباقي على عمومه
- *The general that remains in its generality*  
  - A text that stays upon its full, general scope with no specification.
    - all of you mother and sister will be haram to marry
      - definite by posistion
        - so it will always be haram

** العام المخصوص
- *The general that has been specified*  
  - A general text whose scope has been restricted by another evidence (خاص).
  - indicate general then became specified
    - to Allah to all people is do to hajj - general
      - who ever is able to do so  - specfic
        - in the same ayah
- why do we need to know this
  - when we have two general, and ones been specified vs the one that has never been specified
    - the one that has been never specifed takes precidence
      - e.g tayatul masjid - general
        - prayer in the prohibited time - specific
          - any salah after asr
          - how do we know because there is another hadith that made it specir, the prohpet (ﷺ) praying after asr, when forgot to pray the sunnah of zhur 
          - the general take precedence of the specific
        
          
** العام المراد به الخصوص
- *The general whose intent is the specific*  
  - A general wording where the intended meaning is specific, known from context or other evidence.
    - oh you have believe save your self and your family form the fire, who fuel is mankind
      - we know this is all the kafirs
    - any type of animal is taned becomes pure
      - if the animal dies, you can tan it's skin and it will become pure, the genarity mean all animals, so it could be snake or pig
        - this is the view of imaan ahmend
          -  you can wear a clothes that is tanned from pig
            - shiek shatkiti says it say it a general statement but our logic tells us that it's not pig, like the statement of the fire we know its the kafir and not the mulsulm even thought it says all of mankind as al-nas
** العام الوارد على سبب خاص
- *The general revealed for a specific reason*  
  - A general text that came down due to a particular incident, but its ruling applies in a general way beyond that incident.
    - allah will reaveal aAyat as soon as that incidence will hapne
    - the rulings is based on the words and not based on their specifiec incdience, the laws are taken from the generality of their law 
      
* Closing
And may the peace and blessings of Allah be upon His servant and the seal of the Prophets, Muhammad, his companions and all those who follow his way. Āmīn.
