:PROPERTIES:
:ID:       fc1f0325-07ff-4d1e-977d-148511217a17
:ROAM_ALIASES: halal jaiz permissible
:END:
#+title: Mubah
* Synonyms
•Halal – Something that is permissible/lawful
•Jaa’iz– Something that is allowed
•Mutlaq – Something that is absolute/unrestricted


* linguistically
:PROPERTIES:
:ID:       3fe489fe-4865-42b1-93fe-bfc7ecb2469d
:END:
means something declared or permitted.
* Technically
:PROPERTIES:
:ID:       d9416941-f758-464b-8d72-0045797be5ef
:END:
it refers to
a neutral law
** what is neither connected with a command nor prohibited in and of itself,
like eating during the night of Ramadan.



** excludes
:PROPERTIES:
:ID:       56143647-3c37-420f-97e4-f9753fa641fc
:END:
*** what is connected with a command
:PROPERTIES:
:ID:       37f8731b-2fd9-4b02-94e0-45badfd72790
:END:
- wajib (obligatory)
- mandud (recommended).
*** not something prohibited
:PROPERTIES:
:ID:       6643be50-57ef-458d-a2a9-096232efe2eb
:END:
-  muharram (forbidden)
-  makruh(disliked).

*** in and out itself 
:PROPERTIES:
:ID:       bef6ce76-2df2-4459-8f70-e7aef6162887
:END:
**** excludes anything that acts as a medium leading to a commanded actions
:PROPERTIES:
:ID:       569fb929-2cee-4834-b14c-cfca8344a7af
:END:
- thus becoming obligatory, or leading to a forbidden actions,
- thus becoming prohibited, which would alter its original status as mubah (permissible).
- When something is categorised as mubah (permissible), it remains within the bounds of permissibility, not resulting in reward or punishment for engaging in it.

* Sign of Identification
•The “Forms of Command,” coupled with evidences to lower the rule
 - bring down wajib-> madub -> mubah
 - commanded to hunt, but this comanded come after a prohibitation
•Explicitly offering a choice to the servants of Allah or declaring it halal
 - eg do it if you want, leave it if you want
•Removing complete blame or sin from the perpetrator
 - there not rewasy or sin
•A command to do an action after a prohibition


* Points of Iman
•Every permissible action may take any other ruling
•The default position of permissibility of actions
   - but with worship is the opposite
•Constant engagement in permissible prevents worship to Allah unless!
** According to Imām al-Shāṭibī (al-Muwāfaqāt), mubāḥ is not always permanently neutral.
When done repeatedly, or considered as a whole pattern, it can take the ruling of one of the other four:
 1. Wājib 
 2. Mandūb
 3. Makrūh
 4. Ḥarām
*** Meaning
A neutral action (mubāḥ) can become:
- Recommended or obligatory if the overall pattern leads to benefit.
- Disliked or prohibited if the overall pattern leads to harm.
**** Example
Sleeping is mubāḥ,
but if someone sleeps early to wake for Fajr, it becomes mandūb.
If someone sleeps through prayer, it becomes makrūh or ḥarām.
