:PROPERTIES:
:ID:       6bf72851-0632-43e6-aaa0-9254e3600af7
:END:
#+title:  lessonnotes l7

#+title: Usul al-Fiqh – Lesson 7
#+subtitle: Commands and Prohibitions
#+date: Tuesday 26 November 2024
#+startup: overview

# Module: Usul al-Fiqh 1
# Course book: Usul min 'ilm al-Usul

* Contents
1. Revision of Previous Lesson
2. What a Command necessitates
3. Exceptions and examples
4. “The means take the same ruling as the goals”
5. Principles of Commandments
6. The Prohibitions
7. What a Prohibition necessitates
8. Exercise


* DONE Commands (al-Amr)
*** Definition
A statement that includes the request of an action by way of a high authority.

*** Forms of commandments
- The imperative verb.
- The imperative verbal noun.
- The verbal noun used in place of the imperative verb.
- Present tense verb joined with the lām of imperative.
- Other (contextual forms).

*** What does a command necessitate?
1. The default position of all commands is that they necessitate obligation (wujūb).
2. Actions must be carried out at the earliest time.
3. Fulfilling the commandment once.
4. The prohibition of the opposite.

*** Other meanings of commandments
With the presence of an external indicator (qarīnah), or via the context of a verse, a command could also mean:
1. Something recommended (mustahabb).
2. Something permissible (mubāḥ).
3. A threat.
   


* TODO Prohibitions (an-Nahy)

          
*** What does a prohibition necessitate by defautl?

-----
1. Invalidity of the action if the prohibition returns to “the very thing itself being prohibited”.
   - we went to the hanbli principle example
    -- 
   - we was forbad to fast on a certain days, and he the fast on the day of eid, he did something haram, but is it still valid or not?
     - does a prohibiton nessiate the invlaidty of an action
****** Does a prohibition necessitate the invalidity of the action?

  

-----

- 
*** 

1. Dislike (karāhah).
2. Guidance (irshād).

** KILL Exercise – Qur’an 49:10–12

The believers are nothing else than brothers (in Islâmic religion). So make
reconciliation between your brothers, and fear Allâh, that you may receive
mercy. (10)

O you who believe! Let not a group scoff at another group, it may be that
the latter are better than the former; nor let (some) women scoff at other
women, it may be that the latter are better than the former; nor defame one
another, nor insult one another by nicknames. How bad is it, to insult one's
brother after having Faith [i.e. to call your Muslim brother (a faithful
believer) as: "O sinner", or "O wicked"]. And whosoever does not repent,
then such are indeed Ẓālimūn (wrong-doers). (11)

O you who believe! Avoid much suspicion, indeed some suspicions are sins.
And spy not, neither backbite one another. Would one of you like to eat the
flesh of his dead brother? You would hate it (so hate backbiting). And fear
Allâh. Verily, Allâh is the One Who forgives and accepts repentance, Most
Merciful. (12)

